import type { Bilingual } from '../types';
import type { CcnaDomainId } from './securityCoverage';
import type { SecurityPlane } from './securityTaxonomy';

export type ApplicationSecurityArea = 'resolution' | 'authoritative' | 'resolver' | 'tunneling' | 'tls' | 'http' | 'injection' | 'browser' | 'api';

export interface ApplicationSecurityScenario {
  id: string;
  area: ApplicationSecurityArea;
  domains: CcnaDomainId[];
  planes: SecurityPlane[];
  techniqueIds: string[];
  controlIds: string[];
  title: Bilingual;
  requestPath: Bilingual[];
  threat: Bilingual;
  evidence: Bilingual[];
  controls: Bilingual[];
  verification: Bilingual[];
  caveat: Bilingual;
}

const b = (it: string, en: string): Bilingual => ({ it, en });

export const APPLICATION_SECURITY_SCENARIOS: ApplicationSecurityScenario[] = [
  {
    id: 'dns-resolution-chain', area: 'resolution', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'data'], techniqueIds: ['dns-poisoning'], controlIds: ['dns-application-assurance', 'telemetry-independent-evidence'],
    title: b('Catena di risoluzione DNS e cache', 'DNS resolution chain and caching'),
    requestPath: [b('Lo stub resolver interroga il resolver configurato e ne riceve risposta, TTL e stato di validazione.', 'The stub resolver queries its configured resolver and receives an answer, TTL, and validation state.'), b('Il resolver usa cache o percorre root, TLD e authoritative, verificando referral e deleghe.', 'The resolver uses cache or walks root, TLD, and authoritative servers while checking referrals and delegations.')],
    threat: b('Risposte falsificate, resolver rogue o cache poisoning associano un nome attendibile a una destinazione ostile.', 'Forged replies, rogue resolvers, or cache poisoning map a trusted name to a hostile destination.'),
    evidence: [b('Query/response ID, client, resolver, answer, TTL, rcode e flag AD/CD/DO quando presenti.', 'Query/response ID, client, resolver, answer, TTL, rcode, and AD/CD/DO flags where present.'), b('Confronto tra cache locale, resolver indipendenti e dati authoritative.', 'Comparison among local cache, independent resolvers, and authoritative data.')],
    controls: [b('Resolver gestiti, source validation, randomizzazione, patching e DNSSEC validation dove disponibile.', 'Managed resolvers, source validation, randomization, patching, and DNSSEC validation where available.'), b('DHCP/NAC impediscono resolver non autorizzati; DoH/DoT seguono policy esplicita.', 'DHCP/NAC prevent unauthorized resolvers; DoH/DoT follow explicit policy.')],
    verification: [b('Risolvi un nome di test e correla stub, resolver, cache e authoritative con TTL coerente.', 'Resolve a test name and correlate stub, resolver, cache, and authoritative data with consistent TTLs.'), b('Prova che un client non possa usare un resolver esterno non autorizzato senza evidenza o policy.', 'Prove a client cannot use an unauthorized external resolver without visibility or policy.')],
    caveat: b('Una risposta DNS corretta non prova che il servizio finale o il percorso IP siano affidabili.', 'A correct DNS answer does not prove the final service or IP path is trustworthy.')
  },
  {
    id: 'authoritative-domain-control', area: 'authoritative', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'identity', 'management'], techniqueIds: ['domain-registration-hijack', 'dns-poisoning'], controlIds: ['dns-application-assurance', 'identity-lifecycle-session-control'],
    title: b('Dominio, registrar, delega e DNSSEC', 'Domain, registrar, delegation, and DNSSEC'),
    requestPath: [b('Registrar e registry mantengono ownership, contatti, nameserver e stato del dominio.', 'The registrar and registry maintain ownership, contacts, name servers, and domain status.'), b('La zona authoritative pubblica record e firme; parent DS e DNSKEY formano la chain DNSSEC.', 'The authoritative zone publishes records and signatures; the parent DS and DNSKEY form the DNSSEC chain.')],
    threat: b('Account registrar compromesso, delega alterata o zone transfer esposto dirottano il dominio o rivelano struttura interna.', 'A compromised registrar account, altered delegation, or exposed zone transfer hijacks the domain or reveals internal structure.'),
    evidence: [b('Audit registrar, lock/MFA, modifiche NS/DS, seriale SOA e history della zona.', 'Registrar audit, locks/MFA, NS/DS changes, SOA serial, and zone history.'), b('Chain DNSSEC, scadenza RRSIG, key tag e risposta da ogni authoritative.', 'DNSSEC chain, RRSIG expiry, key tags, and responses from each authoritative server.')],
    controls: [b('Registrar lock, MFA resistente al phishing, ruoli separati e contatti di recovery verificati.', 'Registrar locks, phishing-resistant MFA, separated roles, and verified recovery contacts.'), b('DNSSEC lifecycle, transfer limitato con autenticazione e secondary su failure domain distinti.', 'DNSSEC lifecycle, restricted authenticated transfers, and secondaries across distinct failure domains.')],
    verification: [b('Confronta delega parent, NS authoritative, DS/DNSKEY e firme prima e dopo un change.', 'Compare parent delegation, authoritative NS, DS/DNSKEY, and signatures before and after a change.'), b('Prova recovery e rollover in ambiente controllato senza introdurre una catena bogus.', 'Test recovery and rollover in a controlled environment without introducing a bogus chain.')],
    caveat: b('DNSSEC autentica origine e integrità dei dati DNS; non cifra le query e non impedisce compromissione del registrar o del server finale.', 'DNSSEC authenticates DNS data origin and integrity; it does not encrypt queries or prevent registrar or final-server compromise.')
  },
  {
    id: 'recursive-resolver-boundary', area: 'resolver', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'data'], techniqueIds: ['dns-resource-exhaustion', 'udp-amplification', 'dns-rebinding'], controlIds: ['dns-application-assurance', 'availability-capacity-protection'],
    title: b('Resolver ricorsivo, rebinding e abuso di capacità', 'Recursive resolvers, rebinding, and capacity abuse'),
    requestPath: [b('Il resolver accetta recursion solo da client autorizzati e separa ruoli recursive e authoritative.', 'The resolver accepts recursion only from authorized clients and separates recursive and authoritative roles.'), b('Policy, cache e response controls gestiscono nomi, risposte, rate e destinazioni interne.', 'Policy, caching, and response controls manage names, answers, rates, and internal destinations.')],
    threat: b('Open recursion abilita amplification; random-subdomain esaurisce risorse; DNS rebinding porta un browser verso indirizzi interni.', 'Open recursion enables amplification; random-subdomain traffic exhausts resources; DNS rebinding steers a browser toward internal addresses.'),
    evidence: [b('QPS, cache-hit ratio, recursion clients, response size, SERVFAIL e outstanding query.', 'QPS, cache-hit ratio, recursion clients, response size, SERVFAIL, and outstanding queries.'), b('TTL molto breve, answer che cambia verso RFC1918/link-local e sequenza browser associata.', 'Very short TTLs, answers changing toward RFC1918/link-local addresses, and the associated browser sequence.')],
    controls: [b('Recursion ACL, RRL, egress anti-spoofing, cache e capacity plan per ruolo.', 'Recursion ACLs, RRL, egress anti-spoofing, caching, and role-based capacity planning.'), b('DNS rebinding protection, browser/app origin controls e amministrazione non esposta ai client.', 'DNS rebinding protection, browser/application origin controls, and administration not exposed to clients.')],
    verification: [b('Prova che una sorgente esterna non ottenga recursion e misura la risposta a query controllate.', 'Prove an external source cannot obtain recursion and measure responses to controlled queries.'), b('Usa un dominio di test per confermare blocco o isolamento delle risposte verso address space interno.', 'Use a test domain to confirm blocking or isolation of answers targeting internal address space.')],
    caveat: b('Bloccare risposte private nel DNS riduce alcuni rebinding, ma non sostituisce autenticazione e policy sui servizi interni.', 'Blocking private DNS answers reduces some rebinding but does not replace authentication and policy on internal services.')
  },
  {
    id: 'dns-tunneling-egress', area: 'tunneling', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'data'], techniqueIds: ['dns-tunneling', 'encrypted-traffic-blindness'], controlIds: ['dns-application-assurance', 'telemetry-independent-evidence'],
    title: b('DNS tunneling, DoH e controllo egress', 'DNS tunneling, DoH, and egress control'),
    requestPath: [b('Il client invia nomi al resolver gestito; log e flow collegano identità, query, risposta e destinazione.', 'The client sends names to a managed resolver; logs and flows link identity, query, answer, and destination.'), b('Policy egress distingue resolver approvati, DoH/DoT autorizzato e canali non gestiti.', 'Egress policy distinguishes approved resolvers, authorized DoH/DoT, and unmanaged channels.')],
    threat: b('Label codificate, query ad alta entropia o DoH non autorizzato trasportano comando, controllo o dati fuori rete.', 'Encoded labels, high-entropy queries, or unauthorized DoH carry command-and-control traffic or data out of the network.'),
    evidence: [b('Lunghezza/entropia dei label, record type, NXDOMAIN ratio, periodicità e dominio raro.', 'Label length/entropy, record type, NXDOMAIN ratio, periodicity, and rare domains.'), b('TLS SNI/certificato/IP del provider DoH, process lineage e volume endpoint.', 'TLS SNI/certificate/DoH provider IP, process lineage, and endpoint volume.')],
    controls: [b('Resolver obbligatori, egress filtering, DNS security e allowlist del DoH aziendale.', 'Mandatory resolvers, egress filtering, DNS security, and allowlisting of enterprise DoH.'), b('Detection comportamentale correlata a EDR, proxy e inventory dei domini legittimi.', 'Behavioral detection correlated with EDR, proxy data, and an inventory of legitimate domains.')],
    verification: [b('Genera query benigne ad alta entropia verso un dominio di test e conferma detection senza esfiltrare dati.', 'Generate benign high-entropy queries to a test domain and confirm detection without exfiltrating data.'), b('Prova DNS classico e DoH da processo autorizzato e non autorizzato, verificando policy e log.', 'Test classic DNS and DoH from authorized and unauthorized processes while verifying policy and logs.')],
    caveat: b('Alta entropia o molti NXDOMAIN sono segnali, non prova di tunneling: CDN, security tool e software legittimi possono produrli.', 'High entropy or many NXDOMAIN responses are signals, not proof of tunneling: CDNs, security tools, and legitimate software may produce them.')
  },
  {
    id: 'tls-service-identity', area: 'tls', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'identity', 'data'], techniqueIds: ['tls-downgrade-cert-abuse', 'encrypted-traffic-blindness'], controlIds: ['cryptographic-trust', 'dns-application-assurance'],
    title: b('TLS, identità del servizio e downgrade', 'TLS, service identity, and downgrade'),
    requestPath: [b('Il client risolve il nome, apre la connessione e valida nome, chain, validità e policy del certificato.', 'The client resolves the name, opens the connection, and validates certificate name, chain, validity, and policy.'), b('Handshake negozia versione, cipher suite e chiavi; l’applicazione invia dati solo dopo validazione.', 'The handshake negotiates version, cipher suite, and keys; the application sends data only after validation.')],
    threat: b('Certificati accettati impropriamente, trust store eccessivo o fallback legacy consentono impersonation e downgrade.', 'Improperly accepted certificates, excessive trust stores, or legacy fallback enable impersonation and downgrade.'),
    evidence: [b('SNI/nome, chain, SAN, issuer, seriale, revoca, versione e cipher effettivi.', 'SNI/name, chain, SAN, issuer, serial, revocation, and actual version and cipher.'), b('Client error, handshake trace e confronto con configurazione del load balancer/origin.', 'Client errors, handshake traces, and comparison with load-balancer/origin configuration.')],
    controls: [b('TLS moderno, hostname validation, trust store minimo, lifecycle PKI e HSTS dove appropriato.', 'Modern TLS, hostname validation, minimal trust stores, PKI lifecycle, and HSTS where appropriate.'), b('Disabilitazione del fallback debole e test separati su edge, proxy e origin.', 'Disabled weak fallback and separate tests across edge, proxies, and origins.')],
    verification: [b('Prova client conformi e certificati scaduti, con nome errato o CA non fidata senza bypassare gli errori.', 'Test compliant clients and expired, name-mismatched, or untrusted-CA certificates without bypassing errors.'), b('Osserva la suite realmente negoziata su ogni hop, non solo quella configurata.', 'Observe the suite actually negotiated on each hop, not merely the configured suite.')],
    caveat: b('TLS valido protegge canale e identità secondo la chain; non prova che contenuto, account o server applicativo siano benigni.', 'Valid TLS protects the channel and identity under the chain; it does not prove content, accounts, or the application server are benign.')
  },
  {
    id: 'http-proxy-parsing', area: 'http', domains: ['security-fundamentals'], planes: ['application', 'data'], techniqueIds: ['http-request-smuggling', 'network-reconnaissance'], controlIds: ['dns-application-assurance', 'firewall-ids-ips'],
    title: b('HTTP, reverse proxy e parsing coerente', 'HTTP, reverse proxies, and consistent parsing'),
    requestPath: [b('Client, CDN/WAF, reverse proxy e origin interpretano metodo, host, path, header e body.', 'Client, CDN/WAF, reverse proxy, and origin interpret method, host, path, headers, and body.'), b('Routing e normalizzazione devono produrre la stessa request boundary su ogni hop.', 'Routing and normalization must produce the same request boundary at every hop.')],
    threat: b('Ambiguità Content-Length/Transfer-Encoding, host header o normalizzazione diversa desincronizzano proxy e origin.', 'Content-Length/Transfer-Encoding ambiguity, host headers, or different normalization desynchronize proxies and origins.'),
    evidence: [b('Request ID end-to-end, raw header, connection reuse, response order e backend selected.', 'End-to-end request IDs, raw headers, connection reuse, response order, and selected backend.'), b('Differenza tra access log di edge, proxy e origin per la stessa connessione.', 'Differences among edge, proxy, and origin access logs for the same connection.')],
    controls: [b('Parser coerenti e aggiornati, rifiuto delle ambiguità, normalizzazione e protocollo backend definito.', 'Consistent current parsers, rejection of ambiguity, normalization, and a defined backend protocol.'), b('Host allowlist, routing esplicito, connection handling sicuro e regression test.', 'Host allowlists, explicit routing, safe connection handling, and regression tests.')],
    verification: [b('Invia richieste benigne ambigue in un ambiente di test e conferma un rifiuto coerente su ogni hop.', 'Send benign ambiguous requests in a test environment and confirm consistent rejection at every hop.'), b('Correla request ID e backend per provare che una richiesta produca una sola interpretazione.', 'Correlate request IDs and backends to prove one request produces one interpretation.')],
    caveat: b('Un WAF che registra “blocked” non prova che proxy o origin non abbiano già interpretato o inoltrato parte della richiesta.', 'A WAF “blocked” log does not prove a proxy or origin did not already interpret or forward part of the request.')
  },
  {
    id: 'server-side-injection', area: 'injection', domains: ['security-fundamentals'], planes: ['application', 'identity'], techniqueIds: ['injection'], controlIds: ['dns-application-assurance', 'firewall-ids-ips'],
    title: b('Injection server-side e confine dati–comandi', 'Server-side injection and the data-command boundary'),
    requestPath: [b('L’applicazione valida tipo, formato e autorizzazione dell’input nel contesto della funzione.', 'The application validates input type, format, and authorization in the function context.'), b('Query parametrizzate e API sicure mantengono i dati separati da SQL, shell, template e directory query.', 'Parameterized queries and safe APIs keep data separate from SQL, shell, template, and directory queries.')],
    threat: b('Concatenazione, escaping incoerente o interpreter dinamici trasformano input controllato in comandi o query.', 'Concatenation, inconsistent escaping, or dynamic interpreters turn controlled input into commands or queries.'),
    evidence: [b('Request ID, parametro, validation result, query template e database/process audit.', 'Request ID, parameter, validation result, query template, and database/process auditing.'), b('Errori anomali, timing, child process o query fuori profilo correlati alla richiesta.', 'Abnormal errors, timing, child processes, or out-of-profile queries correlated with the request.')],
    controls: [b('Parametrizzazione, allowlist per tipo, least privilege del service account e secret separati.', 'Parameterization, type-based allowlists, least-privileged service accounts, and separated secrets.'), b('SAST/DAST mirati, code review, WAF come controllo compensativo e logging privo di secret.', 'Targeted SAST/DAST, code review, WAF as a compensating control, and secret-free logging.')],
    verification: [b('Usa payload benigni nel test per provare che restino dati e non cambino struttura o controllo del flusso.', 'Use benign payloads in testing to prove they remain data and do not change structure or control flow.'), b('Conferma che l’account applicativo non possa eseguire operazioni oltre il caso d’uso.', 'Confirm the application account cannot perform operations beyond the use case.')],
    caveat: b('Validare sintassi senza verificare autorizzazione lascia possibili accessi indebiti a oggetti perfettamente validi.', 'Validating syntax without authorization checks still permits improper access to perfectly valid objects.')
  },
  {
    id: 'browser-origin-session', area: 'browser', domains: ['security-fundamentals'], planes: ['application', 'identity'], techniqueIds: ['xss-csrf', 'web-session-cookie-abuse'], controlIds: ['dns-application-assurance', 'identity-lifecycle-session-control'],
    title: b('Browser origin, XSS, CSRF e cookie', 'Browser origins, XSS, CSRF, and cookies'),
    requestPath: [b('Il browser applica same-origin policy, cookie scope e navigazione tra origin.', 'The browser applies the same-origin policy, cookie scope, and cross-origin navigation rules.'), b('L’applicazione esegue output encoding per contesto, anti-CSRF e autorizzazione server-side su ogni azione.', 'The application performs context-aware output encoding, anti-CSRF checks, and server-side authorization for every action.')],
    threat: b('Script iniettato ruba azioni o dati; richieste cross-site sfruttano sessioni già autenticate; cookie deboli ampliano l’abuso.', 'Injected scripts steal actions or data; cross-site requests abuse authenticated sessions; weak cookies expand abuse.'),
    evidence: [b('Origin/Referer, CSP report, sink/source DOM, session ID hash e azione utente correlata.', 'Origin/Referer, CSP reports, DOM sources/sinks, session-ID hashes, and correlated user actions.'), b('Attributi Secure, HttpOnly, SameSite, Domain/Path, rotazione e invalidazione del cookie.', 'Secure, HttpOnly, SameSite, Domain/Path attributes, rotation, and cookie invalidation.')],
    controls: [b('Output encoding per contesto, sanitizzazione mirata, CSP e framework con escaping sicuro.', 'Context-aware output encoding, targeted sanitization, CSP, and frameworks with safe escaping.'), b('Anti-CSRF token, SameSite appropriato, reauthentication per azioni sensibili e session rotation.', 'Anti-CSRF tokens, appropriate SameSite settings, reauthentication for sensitive actions, and session rotation.')],
    verification: [b('Prova input benigni in contesti HTML, attributo, URL e script verificando DOM e CSP.', 'Test benign inputs in HTML, attribute, URL, and script contexts while verifying the DOM and CSP.'), b('Esegui una richiesta cross-site controllata e conferma blocco anche con cookie presente.', 'Perform a controlled cross-site request and confirm blocking even when a cookie is present.')],
    caveat: b('CSP e SameSite riducono il rischio ma non correggono output encoding, autorizzazione o session management errati.', 'CSP and SameSite reduce risk but do not fix incorrect output encoding, authorization, or session management.')
  },
  {
    id: 'api-object-session-control', area: 'api', domains: ['automation-programmability', 'security-fundamentals'], planes: ['application', 'identity', 'management'], techniqueIds: ['api-auth-token-abuse', 'web-session-cookie-abuse', 'injection'], controlIds: ['dns-application-assurance', 'identity-lifecycle-session-control', 'automation-guardrails'],
    title: b('API, autorizzazione degli oggetti e rate control', 'APIs, object authorization, and rate control'),
    requestPath: [b('Gateway e applicazione validano token, audience, issuer, expiry e scope per la richiesta.', 'The gateway and application validate token, audience, issuer, expiry, and scope for the request.'), b('Il servizio applica autorizzazione object-level, schema, idempotenza e limiti per identità e risorsa.', 'The service applies object-level authorization, schemas, idempotency, and limits by identity and resource.')],
    threat: b('Token rubati, ID enumerabili, mass assignment o rate limit globale consentono accesso e modifica fuori ruolo.', 'Stolen tokens, enumerable IDs, mass assignment, or global-only rate limits permit out-of-role access and modification.'),
    evidence: [b('Principal, token ID hash, scope, object ID, decisione authorization e response code.', 'Principal, token-ID hash, scope, object ID, authorization decision, and response code.'), b('Rate per identità/oggetto, schema rejection, audit change e read-back dello stato.', 'Per-identity/object rates, schema rejection, change auditing, and state read-back.')],
    controls: [b('Token brevi e scoped, authorization server-side per oggetto e field allowlist.', 'Short-lived scoped tokens, server-side object authorization, and field allowlists.'), b('Rate/size limit contestuali, schema validation, idempotency key e audit privo di secret.', 'Contextual rate/size limits, schema validation, idempotency keys, and secret-free auditing.')],
    verification: [b('Prova stesso oggetto con owner, altro utente e ruolo amministrativo, verificando deny e audit.', 'Test the same object as its owner, another user, and an administrator while verifying denials and auditing.'), b('Invia campi extra e burst controllati per confermare schema e limiti senza affidarsi al solo HTTP status.', 'Send extra fields and controlled bursts to confirm schemas and limits without relying only on HTTP status.')],
    caveat: b('Autenticazione valida e HTTP 200 non provano autorizzazione corretta, integrità dell’oggetto o risultato applicativo.', 'Valid authentication and HTTP 200 do not prove correct authorization, object integrity, or application outcome.')
  }
];
