import type { Bilingual } from '../types';
import type { CcnaDomainId } from './securityCoverage';

export interface AttackPathStage {
  id: string;
  title: Bilingual;
  objective: Bilingual;
  techniqueIds: string[];
  observable: Bilingual;
  defenseControlIds: string[];
  validation: Bilingual;
}

export interface AttackPath {
  id: string;
  title: Bilingual;
  context: Bilingual;
  impact: Bilingual;
  domains: CcnaDomainId[];
  familyIds: string[];
  stages: AttackPathStage[];
}

const b = (it: string, en: string): Bilingual => ({ it, en });
const s = (id: string, title: Bilingual, objective: Bilingual, techniqueIds: string[], observable: Bilingual, defenseControlIds: string[], validation: Bilingual): AttackPathStage => ({ id, title, objective, techniqueIds, observable, defenseControlIds, validation });
const p = (id: string, title: Bilingual, context: Bilingual, impact: Bilingual, domains: CcnaDomainId[], familyIds: string[], stages: AttackPathStage[]): AttackPath => ({ id, title, context, impact, domains, familyIds, stages });

export const ATTACK_PATHS: AttackPath[] = [
  p('campus-l2-takeover', b('Dall’accesso fisico al controllo del dominio Layer 2', 'From physical access to Layer 2 domain control'), b('Un dispositivo non autorizzato viene collegato a una porta campus lasciata attiva.', 'An unauthorized device is connected to an active campus port.'), b('Intercettazione del traffico locale, deviazione del gateway e perdita di disponibilità.', 'Local traffic interception, gateway redirection, and loss of availability.'), ['network-fundamentals', 'network-access'], ['reconnaissance', 'spoofing', 'mitm', 'availability', 'routing'], [
    s('discover', b('Scoperta del segmento', 'Segment discovery'), b('Raccogliere informazioni su VLAN, apparati e gateway prima di agire.', 'Collect VLAN, device, and gateway information before acting.'), ['cdp-lldp-enumeration', 'network-reconnaissance'], b('Nuovo MAC, frame CDP/LLDP ricevuti e scansione sequenziale di host o porte.', 'A new MAC, received CDP/LLDP frames, and sequential host or port scanning.'), ['physical-media-hardening', 'dot1x-nac', 'telemetry-independent-evidence'], b('Confrontare inventario, autenticazione della porta e baseline NetFlow.', 'Compare inventory, port authentication, and the NetFlow baseline.')),
    s('gain-l2', b('Estensione della raggiungibilità', 'Reachability expansion'), b('Negoziare un trunk o raggiungere VLAN non previste.', 'Negotiate a trunk or reach unintended VLANs.'), ['vlan-switch-spoofing', 'vlan-double-tagging'], b('Trunk inatteso, cambio della modalità switchport o traffico inter-VLAN anomalo.', 'An unexpected trunk, switchport mode change, or abnormal inter-VLAN traffic.'), ['segmentation-least-reachability', 'l2-first-hop-security'], b('Verificare modalità access, DTP disabilitato, native VLAN e allowed list.', 'Verify access mode, disabled DTP, native VLAN, and the allowed list.')),
    s('redirect', b('Deviazione del traffico', 'Traffic redirection'), b('Alterare associazioni IP–MAC o la topologia per inserirsi nel percorso.', 'Alter IP–MAC mappings or topology to enter the traffic path.'), ['arp-poisoning', 'stp-manipulation'], b('Binding ARP variabili, BPDU superiori, root change e topology change.', 'Changing ARP bindings, superior BPDUs, root changes, and topology changes.'), ['l2-first-hop-security', 'stp-edge-protection'], b('Controllare DAI, DHCP Snooping, root bridge previsto e porte inconsistent.', 'Check DAI, DHCP Snooping, the expected root bridge, and inconsistent ports.')),
    s('exhaust', b('Esaurimento delle risorse Layer 2', 'Layer 2 resource exhaustion'), b('Consumare CAM o lease per degradare il servizio e ampliare il flooding.', 'Consume CAM or leases to degrade service and expand flooding.'), ['mac-flooding', 'dhcp-starvation'], b('CAM churn, violazioni Port Security, Discover e pool utilization in crescita.', 'CAM churn, Port Security violations, and rising Discover and pool utilization.'), ['l2-first-hop-security', 'segmentation-least-reachability'], b('Confermare stabilità della CAM, disponibilità del pool e assenza di flooding inatteso.', 'Confirm CAM stability, pool availability, and no unexpected flooding.'))
  ]),
  p('wireless-identity-capture', b('Da evil twin a sessione autenticata', 'From evil twin to authenticated session'), b('Un attaccante imita la WLAN aziendale e forza una nuova associazione.', 'An attacker impersonates the enterprise WLAN and forces a new association.'), b('Furto di identità, accesso non autorizzato e riuso della sessione.', 'Identity theft, unauthorized access, and session reuse.'), ['network-access', 'security-fundamentals'], ['wireless', 'credentials', 'session', 'spoofing'], [
    s('disrupt', b('Disassociazione e pressione radio', 'Disassociation and radio pressure'), b('Ridurre la stabilità della WLAN legittima per indurre la riconnessione.', 'Reduce legitimate WLAN stability to induce reconnection.'), ['rf-jamming', 'evil-twin-deauth'], b('Spike di deauthentication, retry, channel utilization e calo SNR.', 'Spikes in deauthentication, retries, channel utilization, and falling SNR.'), ['physical-media-hardening', 'telemetry-independent-evidence'], b('Correlare WLC, WIDS/WIPS e spectrum analysis per distinguere interferenza e attacco.', 'Correlate WLC, WIDS/WIPS, and spectrum analysis to distinguish interference from attack.')),
    s('imitate', b('Imitazione della WLAN', 'WLAN impersonation'), b('Presentare SSID noto con BSSID e certificato non autorizzati.', 'Present a known SSID with an unauthorized BSSID and certificate.'), ['evil-twin-deauth', 'rogue-device'], b('BSSID duplicato, posizione incoerente e certificato EAP inatteso.', 'A duplicate BSSID, inconsistent location, and unexpected EAP certificate.'), ['dot1x-nac', 'cryptographic-trust'], b('Validare server certificate, chain, nome, BSSID e inventario radio.', 'Validate the server certificate, chain, name, BSSID, and radio inventory.')),
    s('capture', b('Acquisizione dell’identità', 'Identity capture'), b('Ottenere credenziali o materiale di autenticazione riutilizzabile.', 'Obtain credentials or reusable authentication material.'), ['credential-attacks', 'replay'], b('Fallimenti distribuiti, autenticazioni da device nuovo e riuso di challenge o token.', 'Distributed failures, authentication from a new device, and reused challenges or tokens.'), ['aaa-privileged-access', 'dot1x-nac'], b('Confrontare log RADIUS/IdP, device posture, MFA e protezione anti-replay.', 'Compare RADIUS/IdP logs, device posture, MFA, and anti-replay protection.')),
    s('reuse', b('Riuso della sessione', 'Session reuse'), b('Usare token o sessioni sottratte oltre il perimetro wireless.', 'Use stolen tokens or sessions beyond the wireless perimeter.'), ['session-hijack-reset'], b('Token identico da device o rete diversi e variazioni improvvise della sessione.', 'The same token from different devices or networks and abrupt session changes.'), ['aaa-privileged-access', 'segmentation-least-reachability'], b('Revocare la sessione e verificare che la nuova autenticazione richieda identità forte.', 'Revoke the session and verify that reauthentication requires strong identity.'))
  ]),
  p('routing-traffic-detour', b('Deviazione del traffico tramite il control plane', 'Traffic detour through the control plane'), b('Un peer, un neighbor o una sorgente non fidata influenza il percorso IP.', 'An untrusted peer, neighbor, or source influences the IP path.'), b('Blackhole, intercettazione o instabilità della raggiungibilità.', 'Blackholing, interception, or reachability instability.'), ['network-fundamentals', 'ip-connectivity'], ['reconnaissance', 'routing', 'spoofing', 'mitm'], [
    s('map-routing', b('Mappatura del routing', 'Routing reconnaissance'), b('Identificare protocolli, neighbor, prefissi e confini di fiducia.', 'Identify protocols, neighbors, prefixes, and trust boundaries.'), ['network-reconnaissance', 'cdp-lldp-enumeration'], b('Query ripetute, nuove sessioni di gestione e discovery su link di transito.', 'Repeated queries, new management sessions, and discovery on transit links.'), ['segmentation-least-reachability', 'telemetry-independent-evidence'], b('Confrontare neighbor autorizzati, inventario e sorgenti di gestione.', 'Compare authorized neighbors, inventory, and management sources.')),
    s('forge-source', b('Falsificazione della sorgente', 'Source forgery'), b('Mascherare l’origine o sfruttare fiducia basata sull’indirizzo.', 'Hide the origin or exploit address-based trust.'), ['ip-spoofing', 'icmp-redirect-source-route'], b('Sorgenti impossibili, failure uRPF, redirect e pacchetti con IP options.', 'Impossible sources, uRPF failures, redirects, and packets with IP options.'), ['source-validation-copp'], b('Verificare ACL ai confini, uRPF rispetto all’asimmetria e redirect disabilitati.', 'Verify boundary ACLs, uRPF against asymmetry, and disabled redirects.')),
    s('inject-route', b('Inserimento della rotta', 'Route insertion'), b('Introdurre LSA o annunci più specifici per cambiare il best path.', 'Introduce LSAs or more-specific announcements to change the best path.'), ['ospf-injection', 'bgp-hijack'], b('Nuovo advertising router, origin-AS cambiato, neighbor churn o prefisso più specifico.', 'A new advertising router, changed origin AS, neighbor churn, or a more-specific prefix.'), ['routing-trust-policy', 'source-validation-copp'], b('Confrontare LSDB/RIB/FIB, RPKI state, prefix policy e route monitoring esterno.', 'Compare LSDB/RIB/FIB, RPKI state, prefix policy, and external route monitoring.')),
    s('persist-detour', b('Mantenimento della deviazione', 'Detour persistence'), b('Conservare il percorso alterato abbastanza a lungo da intercettare o interrompere.', 'Keep the altered path long enough to intercept or disrupt.'), ['bgp-hijack', 'session-hijack-reset'], b('Traceroute differente, RTT anomalo, reset di sessione e mismatch tra control e data plane.', 'Changed traceroutes, abnormal RTT, session resets, and control/data-plane mismatches.'), ['routing-trust-policy', 'cryptographic-trust', 'telemetry-independent-evidence'], b('Validare il forwarding reale da più punti e l’integrità delle sessioni end-to-end.', 'Validate actual forwarding from multiple vantage points and end-to-end session integrity.'))
  ]),
  p('dns-command-channel', b('Dal resolver al canale di comando nascosto', 'From resolver to hidden command channel'), b('Un endpoint compromesso usa DNS come percorso consentito verso l’esterno.', 'A compromised endpoint uses DNS as an allowed path outward.'), b('Comando e controllo, esfiltrazione o deviazione verso servizi ostili.', 'Command and control, exfiltration, or redirection to hostile services.'), ['ip-services', 'security-fundamentals'], ['reconnaissance', 'injection', 'spoofing', 'credentials'], [
    s('discover-dns', b('Ricognizione del resolver', 'Resolver discovery'), b('Identificare resolver, policy e domini raggiungibili.', 'Identify resolvers, policy, and reachable domains.'), ['network-reconnaissance'], b('Query a record insoliti, resolver alternativi e variazioni nel tasso NXDOMAIN.', 'Queries for unusual records, alternative resolvers, and changes in NXDOMAIN rate.'), ['segmentation-least-reachability', 'telemetry-independent-evidence'], b('Verificare che l’egress DNS raggiunga solo resolver approvati.', 'Verify that DNS egress reaches only approved resolvers.')),
    s('encode', b('Codifica nel protocollo', 'Protocol encoding'), b('Inserire dati o comandi in label e risposte DNS.', 'Insert data or commands into DNS labels and responses.'), ['dns-tunneling', 'injection'], b('Label lunghe o ad alta entropia, domini rari e rapporto query/risposte anomalo.', 'Long or high-entropy labels, rare domains, and abnormal query/response ratios.'), ['firewall-ids-ips', 'telemetry-independent-evidence'], b('Correlare query analytics, endpoint telemetry e volume per identità.', 'Correlate query analytics, endpoint telemetry, and volume by identity.')),
    s('redirect-name', b('Alterazione della risoluzione', 'Resolution manipulation'), b('Restituire record falsi o abusare della fiducia nel resolver.', 'Return forged records or abuse trust in the resolver.'), ['dns-poisoning'], b('DNSSEC failure, TTL insoliti e risposte diverse tra fonti indipendenti.', 'DNSSEC failures, unusual TTLs, and different answers across independent sources.'), ['cryptographic-trust', 'telemetry-independent-evidence'], b('Validare DNSSEC e confrontare resolver, authoritative server e cache.', 'Validate DNSSEC and compare resolvers, authoritative servers, and caches.')),
    s('operate-channel', b('Operatività del canale', 'Channel operation'), b('Mantenere comunicazioni a basso volume evitando soglie statiche.', 'Maintain low-volume communication while avoiding static thresholds.'), ['dns-tunneling', 'api-auth-token-abuse'], b('Periodicità regolare, domini appena creati e token usati da workload inconsueti.', 'Regular periodicity, newly created domains, and tokens used by unusual workloads.'), ['firewall-ids-ips', 'aaa-privileged-access', 'telemetry-independent-evidence'], b('Bloccare il dominio e confermare cessazione sia sul resolver sia sull’endpoint.', 'Block the domain and confirm cessation at both resolver and endpoint.'))
  ]),
  p('management-plane-compromise', b('Dall’identità al controllo degli apparati', 'From identity to device control'), b('Credenziali amministrative o canali di gestione sono esposti o riutilizzati.', 'Administrative credentials or management channels are exposed or reused.'), b('Modifica delle configurazioni, persistenza e perdita di controllo della rete.', 'Configuration changes, persistence, and loss of network control.'), ['ip-services', 'security-fundamentals'], ['credentials', 'session', 'spoofing', 'reconnaissance'], [
    s('find-management', b('Individuazione della superficie di gestione', 'Management surface discovery'), b('Trovare SSH, SNMP, API e fallback locali raggiungibili.', 'Find reachable SSH, SNMP, APIs, and local fallbacks.'), ['network-reconnaissance', 'snmp-community-abuse'], b('Connessioni a porte di gestione, errori SNMP e richieste da reti utente.', 'Connections to management ports, SNMP errors, and requests from user networks.'), ['segmentation-least-reachability', 'firewall-ids-ips'], b('Verificare management ACL, VRF/OOB e servizi realmente in ascolto.', 'Verify management ACLs, VRF/OOB, and services actually listening.')),
    s('obtain-access', b('Ottenimento dell’accesso', 'Access acquisition'), b('Indovinare, riutilizzare o sottrarre un’identità valida.', 'Guess, reuse, or steal a valid identity.'), ['credential-attacks', 'ssh-management-attacks', 'aaa-protocol-abuse'], b('Spraying, fallback AAA, chiavi nuove e accessi fuori profilo.', 'Spraying, AAA fallback, new keys, and out-of-profile access.'), ['aaa-privileged-access', 'cryptographic-trust'], b('Correlare AAA, IdP, command accounting e fingerprint delle chiavi.', 'Correlate AAA, IdP, command accounting, and key fingerprints.')),
    s('take-session', b('Controllo della sessione', 'Session control'), b('Riutilizzare una sessione già autenticata o materiale replayable.', 'Reuse an authenticated session or replayable material.'), ['replay', 'session-hijack-reset'], b('Sessione identica da origini diverse, sequence anomaly o token reuse.', 'The same session from different origins, sequence anomalies, or token reuse.'), ['aaa-privileged-access', 'telemetry-independent-evidence'], b('Revocare sessioni e confermare nuova autenticazione con accounting completo.', 'Revoke sessions and confirm reauthentication with complete accounting.')),
    s('change-network', b('Modifica e persistenza', 'Change and persistence'), b('Alterare configurazioni e telemetria per mantenere accesso e occultare attività.', 'Alter configurations and telemetry to retain access and hide activity.'), ['syslog-manipulation', 'snmp-community-abuse'], b('Configuration diff, gap Syslog, nuovo utente o destinazione di logging cambiata.', 'Configuration diffs, Syslog gaps, a new user, or a changed logging destination.'), ['telemetry-independent-evidence', 'automation-guardrails'], b('Confrontare running config, source of truth, audit remoto e stato reale.', 'Compare running configuration, source of truth, remote audit, and actual state.'))
  ]),
  p('availability-collapse', b('Esaurimento progressivo della disponibilità', 'Progressive availability exhaustion'), b('Traffico riflesso o connessioni incomplete colpiscono più risorse in cascata.', 'Reflected traffic or incomplete connections hit multiple resources in a cascade.'), b('Saturazione del link, delle tabelle di stato e dei servizi essenziali.', 'Saturation of links, state tables, and essential services.'), ['network-fundamentals', 'ip-services', 'security-fundamentals'], ['availability', 'spoofing', 'reconnaissance'], [
    s('profile-service', b('Profilazione del servizio', 'Service profiling'), b('Individuare protocolli esposti, capacità e punti senza rate limit.', 'Identify exposed protocols, capacity, and points without rate limiting.'), ['network-reconnaissance'], b('Scansioni distribuite e richieste di prova verso servizi UDP/TCP.', 'Distributed scans and probe requests to UDP/TCP services.'), ['firewall-ids-ips', 'telemetry-independent-evidence'], b('Confrontare esposizione reale, inventario e baseline delle richieste.', 'Compare actual exposure, inventory, and request baselines.')),
    s('spoof-amplify', b('Riflessione e amplificazione', 'Reflection and amplification'), b('Usare sorgenti falsificate e servizi amplificatori contro il target.', 'Use forged sources and amplifier services against the target.'), ['ip-spoofing', 'udp-amplification'], b('Molte risposte non richieste, sorgenti distribuite e forte asimmetria.', 'Many unsolicited responses, distributed sources, and strong asymmetry.'), ['source-validation-copp', 'segmentation-least-reachability'], b('Validare BCP 38, NetFlow e mitigazione upstream prima del link saturo.', 'Validate BCP 38, NetFlow, and upstream mitigation before link saturation.')),
    s('consume-state', b('Consumo dello stato', 'State consumption'), b('Esaurire backlog, session table o traduzioni NAT.', 'Exhaust backlogs, session tables, or NAT translations.'), ['syn-flood', 'nat-state-exhaustion'], b('Half-open, allocation failure, translation count e CPU in crescita.', 'Rising half-open connections, allocation failures, translation counts, and CPU.'), ['firewall-ids-ips', 'source-validation-copp'], b('Controllare SYN proxy/cookies, timeout, capacity e disponibilità di nuove sessioni.', 'Check SYN proxy/cookies, timeouts, capacity, and new-session availability.')),
    s('degrade-control', b('Impatto sul control plane', 'Control-plane impact'), b('Portare traffico patologico fino alla CPU dell’apparato.', 'Drive pathological traffic to the device CPU.'), ['ip-fragmentation-evasion', 'icmp-redirect-source-route'], b('Punt, fragment reassembly, CoPP drop e instabilità dei protocolli.', 'Punts, fragment reassembly, CoPP drops, and protocol instability.'), ['source-validation-copp', 'telemetry-independent-evidence'], b('Verificare CoPP per classe e stabilità di neighbor, gestione e forwarding.', 'Verify CoPP by class and the stability of neighbors, management, and forwarding.'))
  ]),
  p('trust-and-vpn-subversion', b('Sovversione della fiducia crittografica', 'Cryptographic trust subversion'), b('Un peer o certificato apparentemente valido nasconde parametri deboli o fiducia errata.', 'An apparently valid peer or certificate hides weak parameters or misplaced trust.'), b('Intercettazione, peer non autorizzato o tunnel protetto verso un endpoint ostile.', 'Interception, an unauthorized peer, or a protected tunnel to a hostile endpoint.'), ['security-fundamentals'], ['mitm', 'session', 'spoofing', 'credentials'], [
    s('enumerate-trust', b('Mappatura della fiducia', 'Trust mapping'), b('Identificare CA, peer, suite e dipendenze non aggiornate.', 'Identify CAs, peers, suites, and outdated dependencies.'), ['network-reconnaissance'], b('Handshake di prova, errori di chain e negoziazioni ripetute.', 'Probe handshakes, chain errors, and repeated negotiations.'), ['cryptographic-trust', 'telemetry-independent-evidence'], b('Inventariare trust store, certificati, peer e configurazioni effettive.', 'Inventory trust stores, certificates, peers, and effective configurations.')),
    s('weaken-channel', b('Indebolimento del canale', 'Channel weakening'), b('Forzare downgrade o parametri VPN/TLS non adeguati.', 'Force a downgrade or inadequate VPN/TLS parameters.'), ['tls-downgrade-cert-abuse', 'vpn-weak-crypto'], b('Suite legacy, assenza PFS, peer inatteso o mismatch di policy.', 'Legacy suites, missing PFS, an unexpected peer, or policy mismatch.'), ['cryptographic-trust'], b('Verificare handshake reale, IKE/IPsec SA, rekey e algoritmo negoziato.', 'Verify the actual handshake, IKE/IPsec SAs, rekeying, and negotiated algorithm.')),
    s('abuse-pki', b('Abuso della PKI', 'PKI abuse'), b('Sfruttare una chiave, una CA o un trust store compromessi.', 'Exploit a compromised key, CA, or trust store.'), ['pki-trust-abuse'], b('Seriale inatteso, emissione anomala, revoca ignorata o nuova trust anchor.', 'An unexpected serial, abnormal issuance, ignored revocation, or a new trust anchor.'), ['cryptographic-trust', 'aaa-privileged-access'], b('Controllare nome, chain, CRL/OCSP, CT e accesso alla chiave privata.', 'Check name, chain, CRL/OCSP, CT, and private-key access.')),
    s('reuse-trust', b('Persistenza tramite identità fidata', 'Persistence through trusted identity'), b('Riutilizzare certificati o sessioni valide dopo il primo accesso.', 'Reuse valid certificates or sessions after initial access.'), ['replay', 'session-hijack-reset'], b('Autenticazione valida da contesto nuovo e sessioni dopo la revoca.', 'Valid authentication from a new context and sessions continuing after revocation.'), ['aaa-privileged-access', 'segmentation-least-reachability'], b('Revocare, ruotare e confermare che vecchie identità e sessioni non siano più accettate.', 'Revoke, rotate, and confirm old identities and sessions are no longer accepted.'))
  ]),
  p('automation-blast-radius', b('Compromissione della pipeline e blast radius', 'Pipeline compromise and blast radius'), b('Un token, controller o artifact compromesso propaga modifiche su molti dispositivi.', 'A compromised token, controller, or artifact propagates changes across many devices.'), b('Drift su larga scala, perdita di segmentazione e telemetria non affidabile.', 'Large-scale drift, loss of segmentation, and untrusted telemetry.'), ['automation-programmability', 'security-fundamentals'], ['automation', 'injection', 'credentials'], [
    s('steal-api-access', b('Abuso dell’accesso API', 'API access abuse'), b('Ottenere un token o workload identity con scope eccessivo.', 'Obtain an over-scoped token or workload identity.'), ['api-auth-token-abuse', 'credential-attacks'], b('Token usato da workload, origine o orario nuovi e chiamate fuori profilo.', 'A token used by a new workload, origin, or time and out-of-profile calls.'), ['aaa-privileged-access', 'segmentation-least-reachability'], b('Controllare identity, scope, audience, scadenza e audit delle API.', 'Check identity, scope, audience, expiry, and API auditing.')),
    s('alter-source', b('Alterazione della source of truth', 'Source-of-truth alteration'), b('Inserire input, template o artifact malevoli nella pipeline.', 'Insert malicious input, templates, or artifacts into the pipeline.'), ['automation-supply-chain-drift', 'injection'], b('Hash o firma diversi, dipendenza nuova e diff molto più ampio del ticket.', 'Changed hashes or signatures, a new dependency, and a diff much broader than the ticket.'), ['automation-guardrails', 'cryptographic-trust'], b('Verificare provenienza, firma, schema, peer review e plan/dry-run.', 'Verify provenance, signatures, schemas, peer review, and plans/dry runs.')),
    s('control-fleet', b('Propagazione tramite controller', 'Controller-driven propagation'), b('Usare il controller per distribuire lo stato alterato alla flotta.', 'Use the controller to distribute altered state to the fleet.'), ['controller-compromise'], b('Chiamate southbound insolite, config diff simultanei e canary saltato.', 'Unusual southbound calls, simultaneous configuration diffs, and a skipped canary.'), ['automation-guardrails', 'segmentation-least-reachability'], b('Congelare la propagazione e confrontare intento, controller e dispositivi.', 'Freeze propagation and compare intent, controller state, and devices.')),
    s('poison-observation', b('Manipolazione dell’osservabilità', 'Observability manipulation'), b('Alterare dati o modelli per nascondere il drift o guidare decisioni errate.', 'Alter data or models to hide drift or drive incorrect decisions.'), ['ai-telemetry-poisoning', 'syslog-manipulation'], b('Gap, distribuzioni mutate, confidence anomala e divergenza tra fonti.', 'Gaps, shifted distributions, abnormal confidence, and divergence between sources.'), ['telemetry-independent-evidence', 'automation-guardrails'], b('Confrontare una fonte indipendente e verificare lo stato reale su un campione di device.', 'Compare an independent source and verify actual state on a sample of devices.'))
  ])
];
