import type { Bilingual } from '../types';
import type { CcnaDomainId } from './securityCoverage';
import type { SecurityPlane } from './securityTaxonomy';

export type DefenseFunction = 'prevent' | 'detect' | 'contain' | 'recover' | 'compensate';

export interface DefenseControl {
  id: string;
  name: Bilingual;
  functions: DefenseFunction[];
  planes: SecurityPlane[];
  domains: CcnaDomainId[];
  techniqueIds: string[];
  enforcement: Bilingual;
  dependsOn: Bilingual;
  verify: Bilingual;
  limitation: Bilingual;
}

const b = (it: string, en: string): Bilingual => ({ it, en });
const d = (id: string, name: Bilingual, functions: DefenseFunction[], planes: SecurityPlane[], domains: CcnaDomainId[], techniqueIds: string[], enforcement: Bilingual, dependsOn: Bilingual, verify: Bilingual, limitation: Bilingual): DefenseControl => ({ id, name, functions, planes, domains, techniqueIds, enforcement, dependsOn, verify, limitation });

export const DEFENSE_CONTROLS: DefenseControl[] = [
  d('physical-media-hardening', b('Hardening fisico e del mezzo', 'Physical and media hardening'), ['prevent', 'detect', 'recover'], ['physical'], ['network-fundamentals'], ['physical-tapping', 'rf-jamming', 'rogue-device'], b('Armadi, porte, cablaggi, alimentazione, sensori e controllo dell’accesso fisico.', 'Racks, ports, cabling, power, sensors, and physical access control.'), b('Inventario, ownership, percorsi ridondanti e procedure di ispezione.', 'Inventory, ownership, redundant paths, and inspection procedures.'), b('Audit fisico, tamper evidence, DOM/transceiver e test del percorso alternativo.', 'Physical audit, tamper evidence, DOM/transceiver data, and alternate-path tests.'), b('Non protegge il contenuto intercettato su infrastruttura autorizzata: serve cifratura end-to-end.', 'It does not protect content intercepted on authorized infrastructure: end-to-end encryption is required.')),
  d('segmentation-least-reachability', b('Segmentazione e least reachability', 'Segmentation and least reachability'), ['prevent', 'contain', 'compensate'], ['data', 'management'], ['network-access', 'security-fundamentals'], ['rogue-device', 'vlan-switch-spoofing', 'session-hijack-reset', 'malware-ransomware'], b('VLAN/VRF, ACL, firewall e policy dinamiche limitano chi può raggiungere cosa.', 'VLANs/VRFs, ACLs, firewalls, and dynamic policy limit who can reach what.'), b('Inventario dei flussi, classificazione degli asset e routing simmetrico dove richiesto.', 'Flow inventory, asset classification, and symmetric routing where required.'), b('Test di reachability consentita e negata, ACL counters, route lookup e flow logs.', 'Allowed and denied reachability tests, ACL counters, route lookups, and flow logs.'), b('Una VLAN non è da sola un confine di sicurezza; regole errate possono creare isolamento apparente.', 'A VLAN alone is not a security boundary; incorrect rules may create only apparent isolation.')),
  d('dot1x-nac', b('802.1X, EAP-TLS e NAC', '802.1X, EAP-TLS, and NAC'), ['prevent', 'detect', 'contain'], ['data', 'identity'], ['network-access', 'security-fundamentals'], ['rogue-device', 'nac-posture-bypass', 'evil-twin-deauth'], b('Autentica identità di utente/dispositivo e applica autorizzazione o quarantena per sessione.', 'Authenticates user/device identity and applies per-session authorization or quarantine.'), b('PKI affidabile, RADIUS ridondante, supplicant gestiti e fallback MAB limitato.', 'Trusted PKI, redundant RADIUS, managed supplicants, and restricted MAB fallback.'), b('show authentication sessions details · RADIUS live logs · test di failover.', 'show authentication sessions details · RADIUS live logs · failover tests.'), b('Il profiling non equivale ad autenticazione e un fail-open permissivo può annullare il controllo.', 'Profiling is not authentication, and permissive fail-open behavior can nullify the control.')),
  d('l2-first-hop-security', b('First Hop Security Layer 2', 'Layer 2 First Hop Security'), ['prevent', 'detect', 'contain'], ['data', 'control'], ['network-access', 'ip-services'], ['arp-poisoning', 'rogue-dhcp', 'dhcp-starvation', 'ipv6-ra-nd-spoofing'], b('DHCP Snooping alimenta DAI/IP Source Guard; RA Guard e DHCPv6 Guard proteggono IPv6.', 'DHCP Snooping feeds DAI/IP Source Guard; RA Guard and DHCPv6 Guard protect IPv6.'), b('Trust boundary corretta, binding affidabili, rate coerenti e gestione degli host statici.', 'Correct trust boundaries, reliable bindings, appropriate rates, and handling of static hosts.'), b('Binding, inspection statistics, violation log e test da porte trusted/untrusted.', 'Bindings, inspection statistics, violation logs, and tests from trusted/untrusted ports.'), b('Trust configurato sulla porta sbagliata aggira la difesa; device intermedi possono richiedere policy specifiche.', 'Trust on the wrong port bypasses the defense; intermediate devices may require specific policy.')),
  d('stp-edge-protection', b('Protezioni STP deterministiche', 'Deterministic STP protections'), ['prevent', 'detect', 'contain'], ['control', 'data'], ['network-access'], ['stp-manipulation'], b('Root Guard, BPDU Guard, Loop Guard e root priority proteggono ruoli e topologia.', 'Root Guard, BPDU Guard, Loop Guard, and root priority protect roles and topology.'), b('Classificazione corretta di edge, uplink, link unidirezionali e root previsto.', 'Correct classification of edge ports, uplinks, unidirectional links, and expected root.'), b('show spanning-tree detail · inconsistentports · test controllato della porta edge.', 'show spanning-tree detail · inconsistentports · controlled edge-port test.'), b('Una protezione applicata al ruolo sbagliato può causare outage; non sostituisce il progetto senza loop.', 'A protection applied to the wrong role can cause an outage; it does not replace loop-free design.')),
  d('source-validation-copp', b('Validazione sorgente e CoPP', 'Source validation and CoPP'), ['prevent', 'detect', 'contain', 'compensate'], ['data', 'control'], ['network-fundamentals', 'ip-connectivity'], ['ip-spoofing', 'syn-flood', 'udp-amplification', 'ospf-injection'], b('uRPF/ACL contrastano sorgenti impossibili; CoPP limita traffico destinato alla CPU.', 'uRPF/ACLs counter impossible sources; CoPP limits traffic destined to the CPU.'), b('Conoscenza del routing asimmetrico, classificazione del control plane e baseline dei protocolli.', 'Knowledge of asymmetric routing, control-plane classification, and protocol baselines.'), b('uRPF drop, ACL counters, CoPP class statistics, CPU e adiacenze.', 'uRPF drops, ACL counters, CoPP class statistics, CPU, and adjacencies.'), b('Strict uRPF può scartare traffico legittimo asimmetrico; CoPP non protegge la banda del link.', 'Strict uRPF may drop legitimate asymmetric traffic; CoPP does not protect link bandwidth.')),
  d('routing-trust-policy', b('Fiducia e policy del routing', 'Routing trust and policy'), ['prevent', 'detect', 'contain'], ['control'], ['ip-connectivity'], ['ospf-injection', 'bgp-hijack', 'icmp-redirect-source-route'], b('Autenticazione, passive-interface, prefix/max-prefix policy, RPKI e monitoring degli annunci.', 'Authentication, passive interfaces, prefix/max-prefix policy, RPKI, and announcement monitoring.'), b('Inventario peer, ROA aggiornati, policy versionate e canale di coordinamento upstream.', 'Peer inventory, current ROAs, versioned policy, and an upstream coordination channel.'), b('Neighbor/LSDB, received routes, RPKI state e confronto da collector indipendenti.', 'Neighbor/LSDB data, received routes, RPKI state, and comparison from independent collectors.'), b('RPKI valida l’origine, non l’intero AS path; una policy troppo stretta può isolare prefissi legittimi.', 'RPKI validates origin, not the full AS path; overly strict policy can isolate legitimate prefixes.')),
  d('aaa-privileged-access', b('AAA, MFA e accesso privilegiato', 'AAA, MFA, and privileged access'), ['prevent', 'detect', 'contain', 'recover'], ['management', 'identity'], ['ip-services', 'security-fundamentals'], ['credential-attacks', 'ssh-management-attacks', 'aaa-protocol-abuse'], b('Identità centralizzata, MFA, RBAC, command authorization/accounting e jump host limitano l’amministrazione.', 'Central identity, MFA, RBAC, command authorization/accounting, and jump hosts constrain administration.'), b('Time sync, server AAA ridondanti, fallback locale testato e procedure break-glass.', 'Time synchronization, redundant AAA servers, tested local fallback, and break-glass procedures.'), b('Test AAA, accounting completo, session recording, access review e prova di failover.', 'AAA testing, complete accounting, session recording, access review, and failover testing.'), b('MFA non impedisce abuso di sessioni già autenticate; un fallback errato può creare lockout o bypass.', 'MFA does not prevent abuse of already authenticated sessions; incorrect fallback may cause lockout or bypass.')),
  d('cryptographic-trust', b('Crittografia, PKI e VPN', 'Cryptography, PKI, and VPN'), ['prevent', 'detect', 'recover'], ['data', 'identity'], ['security-fundamentals'], ['physical-tapping', 'tls-downgrade-cert-abuse', 'vpn-weak-crypto', 'pki-trust-abuse'], b('TLS/IPsec, certificati e lifecycle delle chiavi proteggono confidenzialità, integrità e identità dei peer.', 'TLS/IPsec, certificates, and key lifecycle protect confidentiality, integrity, and peer identity.'), b('Trust store minimo, algoritmi moderni, HSM/TPM, revoca e inventario delle dipendenze.', 'Minimal trust stores, modern algorithms, HSM/TPM, revocation, and dependency inventory.'), b('Handshake/suite effettivi, chain/nome, CRL/OCSP, CT e test di rekey.', 'Actual handshakes/suites, chain/name validation, CRL/OCSP, CT, and rekey tests.'), b('La cifratura non rende affidabile un endpoint compromesso e può ridurre la visibilità dei sensori.', 'Encryption does not make a compromised endpoint trustworthy and may reduce sensor visibility.')),
  d('firewall-ids-ips', b('Firewall stateful, IDS e IPS', 'Stateful firewall, IDS, and IPS'), ['prevent', 'detect', 'contain', 'compensate'], ['data', 'application'], ['security-fundamentals'], ['network-reconnaissance', 'injection', 'syn-flood', 'session-hijack-reset'], b('Policy stateful riduce la superficie; IDS osserva, IPS può bloccare inline firme e anomalie.', 'Stateful policy reduces surface; IDS observes, while inline IPS can block signatures and anomalies.'), b('Posizionamento, traffico decifrato dove autorizzato, tuning, capacity e change control.', 'Placement, authorized decrypted traffic, tuning, capacity, and change control.'), b('Rule hit, session log, packet capture, signature event, bypass/fail mode e latency.', 'Rule hits, session logs, packet captures, signature events, bypass/fail modes, and latency.'), b('Falsi positivi e tecniche sconosciute restano possibili; non ferma un DDoS che satura il link a monte.', 'False positives and unknown techniques remain possible; it cannot stop a DDoS saturating the upstream link.')),
  d('telemetry-independent-evidence', b('Telemetria e fonti indipendenti', 'Telemetry and independent sources'), ['detect', 'contain', 'recover', 'compensate'], ['management', 'application'], ['ip-services', 'security-fundamentals'], ['syslog-manipulation', 'snmp-community-abuse', 'ntp-manipulation', 'dns-tunneling'], b('Syslog remoto, NetFlow, SNMPv3, NTP e audit immutabile permettono correlazione e ricostruzione.', 'Remote Syslog, NetFlow, SNMPv3, NTP, and immutable auditing enable correlation and reconstruction.'), b('Timestamp coerenti, collector ridondanti, retention, normalizzazione e controllo degli accessi.', 'Consistent timestamps, redundant collectors, retention, normalization, and access control.'), b('Evento campione end-to-end, gap/duplicate check, integrity e confronto con una fonte indipendente.', 'End-to-end sample event, gap/duplicate checks, integrity, and comparison with an independent source.'), b('La telemetria può essere incompleta, ritardata o manipolata; assenza di evento non prova assenza di attività.', 'Telemetry may be incomplete, delayed, or manipulated; absence of an event does not prove absence of activity.')),
  d('automation-guardrails', b('Guardrail di automazione e recovery', 'Automation guardrails and recovery'), ['prevent', 'detect', 'contain', 'recover'], ['management', 'application'], ['automation-programmability'], ['api-auth-token-abuse', 'controller-compromise', 'automation-supply-chain-drift', 'ai-telemetry-poisoning'], b('Scoped identity, signed artifact, schema validation, plan/dry-run, approval, canary e rollback limitano il blast radius.', 'Scoped identities, signed artifacts, schema validation, plans/dry runs, approvals, canaries, and rollback limit blast radius.'), b('Source of truth, inventory affidabile, backup testato, separazione dei ruoli e audit immutabile.', 'A source of truth, reliable inventory, tested backups, separation of duties, and immutable auditing.'), b('Firma/provenienza, diff previsto/reale, idempotenza, canary health e restore test.', 'Signatures/provenance, intended versus actual diffs, idempotency, canary health, and restore tests.'), b('Un job SUCCESS non garantisce stato corretto; rollback non testato e scope dinamico restano rischi critici.', 'A SUCCESS job does not guarantee correct state; untested rollback and dynamic scope remain critical risks.'))
];
