import type { Bilingual } from '../types';
import type { CcnaDomainId } from './securityCoverage';
import type { SecurityPlane } from './securityTaxonomy';

export type EmailHumanArea = 'authenticity' | 'impersonation' | 'credential' | 'attachment' | 'link' | 'bec' | 'oauth' | 'reporting' | 'response';

export interface EmailHumanSecurityScenario {
  id: string;
  area: EmailHumanArea;
  domains: CcnaDomainId[];
  planes: SecurityPlane[];
  techniqueIds: string[];
  controlIds: string[];
  title: Bilingual;
  deliveryPath: Bilingual[];
  threat: Bilingual;
  evidence: Bilingual[];
  controls: Bilingual[];
  verification: Bilingual[];
  caveat: Bilingual;
}

const b = (it: string, en: string): Bilingual => ({ it, en });

export const EMAIL_HUMAN_SECURITY_SCENARIOS: EmailHumanSecurityScenario[] = [
  {
    id: 'email-domain-authentication', area: 'authenticity', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'identity'], techniqueIds: ['email-authentication-spoofing', 'domain-registration-hijack'], controlIds: ['email-human-assurance', 'dns-application-assurance'],
    title: b('SPF, DKIM, DMARC e allineamento', 'SPF, DKIM, DMARC, and alignment'),
    deliveryPath: [b('Il server ricevente verifica se la sorgente è autorizzata da SPF e valida la firma DKIM sul contenuto firmato.', 'The receiving server checks whether SPF authorizes the source and validates the DKIM signature over signed content.'), b('DMARC confronta l’allineamento del dominio visibile nel From con SPF o DKIM e applica la policy pubblicata.', 'DMARC compares the visible From domain alignment with SPF or DKIM and applies the published policy.')],
    threat: b('Spoofing diretto, servizi terzi non inventariati o forwarding che rompe SPF consentono messaggi ingannevoli o falsi positivi.', 'Direct spoofing, uninventoried third-party senders, or forwarding that breaks SPF enables deceptive messages or false positives.'),
    evidence: [b('Header Authentication-Results, envelope-from, header From, DKIM d=/s= e disposition DMARC.', 'Authentication-Results headers, envelope-from, header From, DKIM d=/s= values, and DMARC disposition.'), b('Report DMARC aggregati/forensi, inventory dei sender e record DNS effettivi.', 'Aggregate/forensic DMARC reports, sender inventory, and actual DNS records.')],
    controls: [b('SPF minimale, DKIM con chiavi gestite e DMARC da monitoring a reject dopo inventory e remediation.', 'Minimal SPF, DKIM with managed keys, and DMARC progression from monitoring to reject after inventory and remediation.'), b('Ownership di dominio e selector, rotazione, subdomain policy e gestione esplicita dei servizi terzi.', 'Ownership of domains and selectors, rotation, subdomain policy, and explicit third-party sender management.')],
    verification: [b('Invia messaggi di test da sender autorizzato, non autorizzato e servizio terzo, leggendo gli header ricevuti.', 'Send test messages from authorized, unauthorized, and third-party senders while reading received headers.'), b('Conferma allineamento relaxed/strict previsto e disposition reale, non solo i record pubblicati.', 'Confirm intended relaxed/strict alignment and actual disposition, not merely published records.')],
    caveat: b('SPF, DKIM e DMARC riducono lo spoofing del dominio; non provano che mittente, account o contenuto siano benigni.', 'SPF, DKIM, and DMARC reduce domain spoofing; they do not prove the sender, account, or content is benign.')
  },
  {
    id: 'lookalike-display-name', area: 'impersonation', domains: ['security-fundamentals', 'ip-services'], planes: ['application', 'identity'], techniqueIds: ['phishing-social-engineering', 'domain-registration-hijack'], controlIds: ['email-human-assurance', 'dns-application-assurance'],
    title: b('Display name, domini lookalike e reply-to', 'Display names, lookalike domains, and reply-to'),
    deliveryPath: [b('Il client mostra display name e indirizzo, mentre gateway e directory valutano dominio, reply-to e relazione con l’identità interna.', 'The client displays a name and address while the gateway and directory evaluate domain, reply-to, and the internal identity relationship.'), b('Brand/domain monitoring confronta omografi, typosquat, nuovi certificati e domini appena registrati.', 'Brand/domain monitoring compares homographs, typosquats, new certificates, and newly registered domains.')],
    threat: b('Un dominio simile o un display name fidato supera DMARC perché l’attaccante autentica correttamente il proprio dominio.', 'A similar domain or trusted display name passes DMARC because the attacker correctly authenticates their own domain.'),
    evidence: [b('Header From/Reply-To/Return-Path, punycode, età del dominio e prima comunicazione tra mittente e destinatario.', 'From/Reply-To/Return-Path headers, punycode, domain age, and first communication between sender and recipient.'), b('Certificate transparency, passive DNS e similarità con domini/nomi protetti.', 'Certificate Transparency, passive DNS, and similarity to protected domains/names.')],
    controls: [b('Banner per external/first-contact, anti-impersonation su utenti VIP e blocco dei domini lookalike confermati.', 'External/first-contact banners, anti-impersonation for VIP users, and blocking of confirmed lookalike domains.'), b('Registrazione difensiva selettiva, monitoring e verifica out-of-band per richieste sensibili.', 'Selective defensive registration, monitoring, and out-of-band verification for sensitive requests.')],
    verification: [b('Usa domini controllati simili e display name di test per verificare banner, detection e quarantena.', 'Use controlled similar domains and test display names to verify banners, detection, and quarantine.'), b('Conferma che reply-to diverso e punycode restino visibili all’analista e, dove possibile, all’utente.', 'Confirm differing reply-to and punycode remain visible to analysts and, where possible, users.')],
    caveat: b('DMARC pass non significa identità aziendale verificata: un dominio lookalike può essere perfettamente autenticato.', 'DMARC pass does not mean verified corporate identity: a lookalike domain can be perfectly authenticated.')
  },
  {
    id: 'credential-aitm-phishing', area: 'credential', domains: ['security-fundamentals'], planes: ['identity', 'application'], techniqueIds: ['phishing-social-engineering', 'credential-attacks', 'adversary-in-the-middle-phishing', 'web-session-cookie-abuse'], controlIds: ['email-human-assurance', 'identity-lifecycle-session-control'],
    title: b('Credential phishing, reverse proxy e session theft', 'Credential phishing, reverse proxies, and session theft'),
    deliveryPath: [b('Il link porta a un sito clone o a un reverse proxy che inoltra in tempo reale il login verso il servizio vero.', 'The link leads to a cloned site or reverse proxy that forwards login to the real service in real time.'), b('Password, MFA e cookie di sessione possono essere intercettati prima che il browser raggiunga l’applicazione reale.', 'Passwords, MFA, and session cookies may be intercepted before the browser reaches the real application.')],
    threat: b('MFA push, OTP o SMS possono essere relayati; il cookie rubato riusa una sessione già autenticata.', 'Push MFA, OTPs, or SMS codes can be relayed; a stolen cookie reuses an already authenticated session.'),
    evidence: [b('URL/referrer, certificate/domain, IdP sign-in, device/IP, token ID e sessione associata.', 'URL/referrer, certificate/domain, IdP sign-in, device/IP, token ID, and associated session.'), b('Impossible travel contestualizzato, nuovo device, binding assente e uso del cookie dopo il login.', 'Contextualized impossible travel, a new device, missing binding, and cookie use after login.')],
    controls: [b('MFA resistente al phishing con FIDO2/WebAuthn, device binding e conditional access.', 'Phishing-resistant FIDO2/WebAuthn MFA, device binding, and conditional access.'), b('Safe links/browser isolation, password manager con origin matching e sessioni brevi/revocabili.', 'Safe links/browser isolation, password managers with origin matching, and short revocable sessions.')],
    verification: [b('In un tenant di test, prova che una credenziale valida non basti da origin o device non conforme.', 'In a test tenant, prove valid credentials are insufficient from a noncompliant origin or device.'), b('Revoca una sessione di test e conferma che cookie e refresh token non restino utilizzabili.', 'Revoke a test session and confirm cookies and refresh tokens no longer work.')],
    caveat: b('MFA non resistente al phishing può essere aggirata in tempo reale; cambiare la password non revoca automaticamente ogni sessione.', 'Non-phishing-resistant MFA can be bypassed in real time; changing a password does not automatically revoke every session.')
  },
  {
    id: 'malicious-attachment-chain', area: 'attachment', domains: ['security-fundamentals'], planes: ['application', 'identity'], techniqueIds: ['phishing-social-engineering', 'malware-ransomware', 'application-control-bypass'], controlIds: ['email-human-assurance', 'endpoint-security-assurance'],
    title: b('Allegati, archivi, macro e payload', 'Attachments, archives, macros, and payloads'),
    deliveryPath: [b('Gateway analizza tipo reale, archivio, firma, reputazione e comportamento in sandbox.', 'The gateway analyzes true file type, archives, signatures, reputation, and sandbox behavior.'), b('Endpoint applica protected view, macro policy, application control ed EDR quando l’utente apre il file.', 'The endpoint applies protected view, macro policy, application control, and EDR when the user opens the file.')],
    threat: b('Archivi protetti, file container, macro, shortcut o formati poliglotti aggirano analisi e avviano interpreti attendibili.', 'Protected archives, container files, macros, shortcuts, or polyglot formats evade analysis and launch trusted interpreters.'),
    evidence: [b('MIME e magic bytes, hash, archive tree, firma, sandbox process tree e callback di rete.', 'MIME and magic bytes, hashes, archive trees, signatures, sandbox process trees, and network callbacks.'), b('File origin, Mark-of-the-Web o equivalente, parent-child endpoint e decisione application control.', 'File origin, Mark-of-the-Web or equivalent, endpoint parent-child chain, and application-control decision.')],
    controls: [b('Blocco dei tipi non necessari, content disarm/reconstruction e sandbox con limiti noti.', 'Blocking unnecessary types, content disarm/reconstruction, and sandboxing with known limitations.'), b('Macro da fonti fidate, application control, least privilege, EDR e segmentazione egress.', 'Macros from trusted sources, application control, least privilege, EDR, and egress segmentation.')],
    verification: [b('Invia artefatti benigni di test per ogni formato consentito e conferma gateway, client ed endpoint.', 'Send benign test artifacts for each allowed format and confirm gateway, client, and endpoint behavior.'), b('Verifica che un archivio cifrato richieda un percorso controllato invece di bypass automatico.', 'Verify an encrypted archive requires a controlled path instead of automatic bypass.')],
    caveat: b('Sandbox clean non prova sicurezza: delay, dipendenze ambientali e formati non emulati possono nascondere il comportamento.', 'A clean sandbox verdict does not prove safety: delays, environmental dependencies, and unemulated formats may hide behavior.')
  },
  {
    id: 'url-qr-redirect-chain', area: 'link', domains: ['ip-services', 'security-fundamentals'], planes: ['application', 'data'], techniqueIds: ['phishing-social-engineering', 'dns-poisoning', 'tls-downgrade-cert-abuse'], controlIds: ['email-human-assurance', 'dns-application-assurance'],
    title: b('URL, QR code, shortener e redirect', 'URLs, QR codes, shorteners, and redirects'),
    deliveryPath: [b('Gateway riscrive o valuta URL; browser e DNS risolvono la destinazione quando avviene il click.', 'The gateway rewrites or evaluates URLs; the browser and DNS resolve the destination at click time.'), b('Redirect, shortener, QR e contenuti condizionali possono cambiare destinazione dopo la consegna.', 'Redirects, shorteners, QR codes, and conditional content may change the destination after delivery.')],
    threat: b('Catene di redirect, compromissione post-delivery o QR spostano il controllo fuori dall’analisi iniziale del messaggio.', 'Redirect chains, post-delivery compromise, or QR codes move control beyond initial message analysis.'),
    evidence: [b('URL originale/riscritto, redirect chain, DNS/TLS al click, categoria e timestamp.', 'Original/rewritten URLs, redirect chains, click-time DNS/TLS, category, and timestamp.'), b('QR decoded value, browser process, download e successivi eventi IdP/endpoint.', 'Decoded QR value, browser process, downloads, and subsequent IdP/endpoint events.')],
    controls: [b('Time-of-click analysis, browser isolation per rischio, DNS/web filtering e blocco dei domini appena registrati calibrato.', 'Time-of-click analysis, risk-based browser isolation, DNS/web filtering, and calibrated blocking of newly registered domains.'), b('Decodifica QR, limite dei redirect, inspection coerente su device gestiti e reporting semplice.', 'QR decoding, redirect limits, consistent inspection on managed devices, and simple reporting.')],
    verification: [b('Usa URL e QR di test con redirect controllati e modifica benignamente la destinazione dopo la consegna.', 'Use test URLs and QR codes with controlled redirects and benignly change the destination after delivery.'), b('Conferma stessa policy da client desktop, mobile e webmail senza esporre dati reali.', 'Confirm the same policy from desktop, mobile, and webmail clients without exposing real data.')],
    caveat: b('HTTPS e lucchetto provano il canale verso il dominio visualizzato, non che il dominio o la pagina siano legittimi.', 'HTTPS and the padlock prove the channel to the displayed domain, not that the domain or page is legitimate.')
  },
  {
    id: 'business-email-compromise', area: 'bec', domains: ['security-fundamentals'], planes: ['identity', 'application'], techniqueIds: ['business-email-compromise', 'phishing-social-engineering', 'credential-attacks'], controlIds: ['email-human-assurance', 'identity-lifecycle-session-control'],
    title: b('BEC, thread hijack e frode di processo', 'BEC, thread hijacking, and process fraud'),
    deliveryPath: [b('Un account compromesso o impersonato usa contesto reale, thread e rapporti organizzativi per formulare la richiesta.', 'A compromised or impersonated account uses real context, threads, and organizational relationships to craft the request.'), b('Il processo aziendale decide pagamento, modifica IBAN, dati o accessi tramite verifiche tecniche e umane.', 'The business process decides payments, bank-detail changes, data release, or access through technical and human checks.')],
    threat: b('Una mail senza link o malware può essere autentica e provenire da un account reale, ma chiedere un’azione fraudolenta.', 'An email without links or malware may be authentic and come from a real account while requesting a fraudulent action.'),
    evidence: [b('Sign-in/account audit, inbox rule, forwarding, sent/deleted item e cambio stile/relazione.', 'Sign-in/account auditing, inbox rules, forwarding, sent/deleted items, and changes in style/relationship.'), b('Change di pagamento, callback, approvazioni, beneficiary history e timeline finanziaria.', 'Payment changes, callbacks, approvals, beneficiary history, and financial timeline.')],
    controls: [b('Doppia approvazione, callback su contatto noto e separazione dei ruoli per variazioni sensibili.', 'Dual approval, callbacks through known contacts, and separation of duties for sensitive changes.'), b('MFA resistente al phishing, alert su forwarding/rule e anomaly detection contestualizzata.', 'Phishing-resistant MFA, forwarding/rule alerts, and contextualized anomaly detection.')],
    verification: [b('Esegui un tabletop con richiesta fittizia di cambio IBAN e misura i controlli del processo, non il solo filtro mail.', 'Run a tabletop with a fictitious bank-detail change and measure process controls, not merely mail filtering.'), b('Crea una inbox rule innocua in test e conferma detection, ownership e risposta.', 'Create a harmless inbox rule in testing and confirm detection, ownership, and response.')],
    caveat: b('Email autenticata e account reale non rendono legittima la richiesta: il controllo decisivo può essere nel processo aziendale.', 'Authenticated email and a real account do not make a request legitimate: the decisive control may be in the business process.')
  },
  {
    id: 'malicious-oauth-consent', area: 'oauth', domains: ['security-fundamentals', 'automation-programmability'], planes: ['identity', 'application', 'management'], techniqueIds: ['malicious-oauth-consent', 'api-auth-token-abuse', 'phishing-social-engineering'], controlIds: ['email-human-assurance', 'identity-lifecycle-session-control', 'automation-guardrails'],
    title: b('OAuth consent phishing e applicazioni malevole', 'OAuth consent phishing and malicious applications'),
    deliveryPath: [b('Il link apre il vero IdP e presenta un’applicazione che richiede scope su posta, file, profilo o API.', 'The link opens the real IdP and presents an application requesting scopes over mail, files, profile data, or APIs.'), b('Dopo il consenso, token e refresh token consentono accesso senza conoscere la password.', 'After consent, access and refresh tokens permit access without knowing the password.')],
    threat: b('L’utente vede dominio e login legittimi ma concede permessi eccessivi a un’app controllata dall’attaccante.', 'The user sees a legitimate domain and login but grants excessive permissions to an attacker-controlled application.'),
    evidence: [b('App/client ID, publisher verification, redirect URI, requested/granted scope e consenting principal.', 'App/client ID, publisher verification, redirect URI, requested/granted scopes, and consenting principal.'), b('Token issuance/use, API calls, mailbox/file access e persistence del service principal.', 'Token issuance/use, API calls, mailbox/file access, and service-principal persistence.')],
    controls: [b('User consent limitato, admin approval workflow, verified publisher e scope allowlist.', 'Restricted user consent, admin approval workflows, verified publishers, and scope allowlists.'), b('App governance, token monitoring, access review e lifecycle dei service principal.', 'Application governance, token monitoring, access reviews, and service-principal lifecycle.')],
    verification: [b('In tenant di test richiedi scope minimo e sovradimensionato, verificando approvazione e audit.', 'In a test tenant request minimal and excessive scopes while verifying approval and auditing.'), b('Revoca grant e service principal e conferma invalidazione di access e refresh token.', 'Revoke the grant and service principal and confirm invalidation of access and refresh tokens.')],
    caveat: b('Revocare la password non elimina un grant OAuth; occorre revocare consenso, token e persistenza applicativa.', 'Revoking a password does not remove an OAuth grant; consent, tokens, and application persistence must be revoked.')
  },
  {
    id: 'user-report-triage', area: 'reporting', domains: ['security-fundamentals'], planes: ['application', 'identity', 'management'], techniqueIds: ['phishing-social-engineering', 'business-email-compromise'], controlIds: ['email-human-assurance', 'telemetry-independent-evidence'],
    title: b('Segnalazione dell’utente e triage evidence-first', 'User reporting and evidence-first triage'),
    deliveryPath: [b('Il pulsante di reporting conserva messaggio originale, header, allegati, URL e contesto del destinatario.', 'The reporting button preserves the original message, headers, attachments, URLs, and recipient context.'), b('Il triage correla campagna, sender, delivery, click, identity ed endpoint prima di classificare e contenere.', 'Triage correlates campaign, sender, delivery, clicks, identity, and endpoints before classification and containment.')],
    threat: b('Screenshot o inoltro perdono header e artefatti; la chiusura come spam può ignorare click, credenziali o messaggi gemelli.', 'Screenshots or forwarding lose headers and artifacts; closing as spam may ignore clicks, credentials, or sibling messages.'),
    evidence: [b('Message ID, trace, raw MIME/header, recipients, URL/attachment hash e verdict versionato.', 'Message ID, trace, raw MIME/headers, recipients, URL/attachment hashes, and a versioned verdict.'), b('Click log, IdP sign-in/session, EDR timeline e azioni già eseguite.', 'Click logs, IdP sign-ins/sessions, EDR timelines, and actions already taken.')],
    controls: [b('Reporting one-click, acknowledgement, SLA per rischio e playbook che preserva evidenze.', 'One-click reporting, acknowledgement, risk-based SLAs, and evidence-preserving playbooks.'), b('Search-and-purge governato, sandbox/reputation aggiornabili e feedback senza colpevolizzazione.', 'Governed search-and-purge, updateable sandbox/reputation verdicts, and blame-free feedback.')],
    verification: [b('Invia un messaggio benigno di simulazione tecnica e seguilo da report a triage, correlazione e chiusura.', 'Send a benign technical simulation message and follow it from reporting through triage, correlation, and closure.'), b('Conferma che la ricerca trovi copie modificate e che purge mantenga audit e possibilità di recovery.', 'Confirm searches find modified copies and purge preserves auditing and recoverability.')],
    caveat: b('La segnalazione umana è una fonte preziosa ma incompleta; assenza di report non prova assenza di consegna o interazione.', 'Human reporting is valuable but incomplete; absence of reports does not prove absence of delivery or interaction.')
  },
  {
    id: 'phishing-containment-recovery', area: 'response', domains: ['security-fundamentals'], planes: ['identity', 'application', 'management'], techniqueIds: ['phishing-social-engineering', 'credential-attacks', 'web-session-cookie-abuse', 'malicious-oauth-consent'], controlIds: ['email-human-assurance', 'identity-lifecycle-session-control', 'endpoint-security-assurance'],
    title: b('Contenimento e recovery dopo il phishing', 'Containment and recovery after phishing'),
    deliveryPath: [b('La risposta definisce chi ha ricevuto, aperto, cliccato, autenticato, consentito o eseguito contenuto.', 'Response determines who received, opened, clicked, authenticated, granted consent, or executed content.'), b('Containment coordina mail, IdP, token/sessioni, endpoint, DNS/proxy e processi aziendali coinvolti.', 'Containment coordinates mail, the IdP, tokens/sessions, endpoints, DNS/proxy controls, and affected business processes.')],
    threat: b('Eliminare la mail o cambiare la password lascia possibili sessioni, token OAuth, inbox rule, malware e frodi già avviate.', 'Deleting the email or changing the password may leave sessions, OAuth tokens, inbox rules, malware, and initiated fraud intact.'),
    evidence: [b('Delivery/open/click, sign-in, MFA, token/grant, rule/forwarding, endpoint process e transazioni.', 'Delivery/open/click data, sign-ins, MFA, tokens/grants, rules/forwarding, endpoint processes, and transactions.'), b('Timeline comune, scope degli utenti/asset e conferma delle azioni di revoca o purge.', 'A common timeline, user/asset scope, and confirmation of revocation or purge actions.')],
    controls: [b('Purge, blocco artefatti, revoke session/token/grant, reset credenziali e isolamento endpoint secondo evidenza.', 'Purge, artifact blocking, session/token/grant revocation, credential resets, and evidence-based endpoint isolation.'), b('Verifica pagamenti/dati, hunting dei messaggi gemelli e monitoraggio rafforzato dopo riammissione.', 'Payment/data verification, hunting for sibling messages, and enhanced monitoring after readmission.')],
    verification: [b('Conferma che messaggi, URL, sessioni, grant e persistenza non siano più utilizzabili in un account di test.', 'Confirm messages, URLs, sessions, grants, and persistence are no longer usable in a test account.'), b('Rivalida endpoint, identità e processo aziendale prima di chiudere l’incidente.', 'Revalidate the endpoint, identity, and business process before closing the incident.')],
    caveat: b('Il reset della password è solo una delle azioni: sessioni, refresh token, grant OAuth e persistenza devono essere verificati separatamente.', 'Password reset is only one action: sessions, refresh tokens, OAuth grants, and persistence must be checked separately.')
  }
];
