import type { Bilingual } from '../types';
import type { CcnaDomainId } from './securityCoverage';
import type { SecurityPlane } from './securityTaxonomy';

export type EndpointSecurityArea = 'inventory' | 'baseline' | 'patching' | 'edr' | 'firewall' | 'application' | 'posture' | 'privilege' | 'containment';

export interface EndpointSecurityScenario {
  id: string;
  area: EndpointSecurityArea;
  domains: CcnaDomainId[];
  planes: SecurityPlane[];
  techniqueIds: string[];
  controlIds: string[];
  title: Bilingual;
  lifecycle: Bilingual[];
  threat: Bilingual;
  evidence: Bilingual[];
  controls: Bilingual[];
  verification: Bilingual[];
  caveat: Bilingual;
}

const b = (it: string, en: string): Bilingual => ({ it, en });

export const ENDPOINT_SECURITY_SCENARIOS: EndpointSecurityScenario[] = [
  {
    id: 'endpoint-inventory-ownership', area: 'inventory', domains: ['network-access', 'security-fundamentals'], planes: ['data', 'identity', 'management'], techniqueIds: ['rogue-device', 'network-reconnaissance'], controlIds: ['dot1x-nac', 'endpoint-security-assurance'],
    title: b('Inventario, ownership e dispositivi non gestiti', 'Inventory, ownership, and unmanaged devices'),
    lifecycle: [b('DHCP, switch, wireless, NAC e directory osservano un dispositivo da punti diversi.', 'DHCP, switching, wireless, NAC, and directory services observe a device from different vantage points.'), b('L’inventario riconcilia identità, owner, seriale, sistema operativo, stato di gestione e ultima presenza.', 'Inventory reconciles identity, owner, serial number, operating system, management state, and last seen time.')],
    threat: b('Asset sconosciuti o duplicati entrano nella rete senza owner, baseline o agente di sicurezza verificabili.', 'Unknown or duplicate assets enter the network without a verifiable owner, baseline, or security agent.'),
    evidence: [b('Sessione NAC, MAC/IP/porta, certificato device, MDM/EDR ID e record CMDB.', 'NAC session, MAC/IP/port, device certificate, MDM/EDR ID, and CMDB record.'), b('Delta tra dispositivi visti in rete e dispositivi dichiarati gestiti.', 'Differences between network-seen devices and devices declared as managed.')],
    controls: [b('802.1X/EAP-TLS per i device gestiti, segmenti limitati per guest e dispositivi senza supplicant.', '802.1X/EAP-TLS for managed devices and restricted segments for guests and devices without a supplicant.'), b('Riconciliazione automatica, owner obbligatorio, scadenza e quarantena degli asset orfani.', 'Automated reconciliation, mandatory ownership, expiry, and quarantine for orphaned assets.')],
    verification: [b('Collega un device gestito e uno sconosciuto e conferma identità, policy e segmento assegnati.', 'Connect a managed and an unknown device and confirm assigned identity, policy, and segment.'), b('Verifica che la rimozione dalla gestione produca un delta e una risposta entro la finestra prevista.', 'Verify that removal from management produces a delta and response within the intended window.')],
    caveat: b('Un MAC, hostname o profilo osservato identifica debolmente un asset; non equivale a proprietà o integrità dimostrate.', 'An observed MAC address, hostname, or profile weakly identifies an asset; it is not proof of ownership or integrity.')
  },
  {
    id: 'secure-endpoint-baseline', area: 'baseline', domains: ['security-fundamentals', 'automation-programmability'], planes: ['application', 'management'], techniqueIds: ['endpoint-configuration-drift', 'privileged-command-abuse'], controlIds: ['automation-guardrails', 'endpoint-security-assurance'],
    title: b('Baseline sicura e configuration drift', 'Secure baseline and configuration drift'),
    lifecycle: [b('Una baseline versionata definisce servizi, cifratura, audit, account, browser e impostazioni di protezione.', 'A versioned baseline defines services, encryption, auditing, accounts, browsers, and protection settings.'), b('MDM o configuration management misura e corregge il drift secondo eccezioni approvate e scadenza.', 'MDM or configuration management measures and remediates drift under approved, expiring exceptions.')],
    threat: b('Servizi riabilitati, audit disattivato o eccezioni permanenti creano percorsi di persistenza e perdita di visibilità.', 'Re-enabled services, disabled auditing, or permanent exceptions create persistence paths and loss of visibility.'),
    evidence: [b('Baseline/versione applicata, compliance result, setting divergente e change associato.', 'Applied baseline/version, compliance result, divergent setting, and associated change.'), b('Confronto tra policy centrale, configurazione locale e comportamento effettivo.', 'Comparison among central policy, local configuration, and actual behavior.')],
    controls: [b('Baseline per ruolo, least functionality, cifratura disco, logging, screen lock e servizi minimi.', 'Role-based baselines, least functionality, disk encryption, logging, screen lock, and minimal services.'), b('Eccezioni con owner e scadenza, rollout a canary e rollback provato.', 'Exceptions with owners and expiry, canary rollouts, and proven rollback.')],
    verification: [b('Modifica in lab un setting controllato e conferma detection, attribution e remediation.', 'Change a controlled setting in a lab and confirm detection, attribution, and remediation.'), b('Prova che la baseline non interrompa il ruolo operativo prima del rollout esteso.', 'Prove the baseline does not break the operational role before broad rollout.')],
    caveat: b('Lo stato “compliant” è una misura puntuale e può essere obsoleto; non prova che il controllo sia rimasto efficace tra due scansioni.', 'A “compliant” state is point-in-time and may be stale; it does not prove the control remained effective between scans.')
  },
  {
    id: 'risk-based-patching', area: 'patching', domains: ['security-fundamentals'], planes: ['application', 'management'], techniqueIds: ['unpatched-endpoint-exploitation'], controlIds: ['endpoint-security-assurance', 'segmentation-least-reachability'],
    title: b('Patching basato sul rischio e vulnerabilità', 'Risk-based patching and vulnerabilities'),
    lifecycle: [b('Inventario software e scanner associano prodotto, versione e configurazione a vulnerabilità applicabili.', 'Software inventory and scanners map product, version, and configuration to applicable vulnerabilities.'), b('Priorità combina exploitability, esposizione, valore dell’asset e controlli compensativi prima del deploy.', 'Prioritization combines exploitability, exposure, asset value, and compensating controls before deployment.')],
    threat: b('Una vulnerabilità sfruttabile resta esposta perché il solo CVSS, una scansione autenticata fallita o un reboot mancante falsano lo stato.', 'An exploitable vulnerability remains exposed because CVSS alone, a failed authenticated scan, or a missing reboot misrepresents status.'),
    evidence: [b('CVE/applicabilità, package o build installata, scan credentialed e stato reboot.', 'CVE applicability, installed package or build, credentialed scan, and reboot state.'), b('Exploit evidence controllata, exposure path e protezione compensativa verificata.', 'Controlled exploit evidence, exposure path, and verified compensating protection.')],
    controls: [b('SLA per rischio, staged rollout, backup/rollback e manutenzione delle dipendenze.', 'Risk-based SLAs, staged rollout, backup/rollback, and dependency maintenance.'), b('Isolamento o virtual patching temporaneo quando la patch non è subito applicabile.', 'Temporary isolation or virtual patching when the patch cannot be applied immediately.')],
    verification: [b('Conferma versione/build e ripeti la detection autenticata dopo installazione e reboot.', 'Confirm version/build and repeat authenticated detection after installation and reboot.'), b('Riesegui test funzionali e di esposizione, non il solo installer success.', 'Repeat functional and exposure tests, not merely the installer success state.')],
    caveat: b('Patch installata non prova vulnerabilità rimossa: versione, configurazione, reboot e percorso di attacco devono essere rivalidati.', 'An installed patch does not prove the vulnerability is removed: version, configuration, reboot, and attack path must be revalidated.')
  },
  {
    id: 'edr-coverage-tamper', area: 'edr', domains: ['security-fundamentals'], planes: ['application', 'management'], techniqueIds: ['endpoint-agent-tampering', 'malware-ransomware', 'security-log-suppression'], controlIds: ['endpoint-security-assurance', 'telemetry-independent-evidence'],
    title: b('Copertura EDR, sensor health e tamper protection', 'EDR coverage, sensor health, and tamper protection'),
    lifecycle: [b('L’agente raccoglie processi, parent-child, file, rete, identità e segnali di memoria.', 'The agent collects process, parent-child, file, network, identity, and memory signals.'), b('La piattaforma applica detection e response, mentre health e inventory dimostrano quali endpoint sono realmente coperti.', 'The platform applies detection and response while health and inventory establish which endpoints are actually covered.')],
    threat: b('Un agente disabilitato, in modalità degradata o escluso da una policy crea un blind spot pur risultando installato.', 'A disabled, degraded, or policy-excluded agent creates a blind spot even though it appears installed.'),
    evidence: [b('Heartbeat, policy/versione, sensor mode, queue, exclusion e tamper event.', 'Heartbeat, policy/version, sensor mode, queue, exclusions, and tamper events.'), b('Correlazione tra processo benigno di test, evento EDR, log OS e flusso di rete.', 'Correlation among a benign test process, EDR event, OS log, and network flow.')],
    controls: [b('Tamper protection, ruoli separati, policy minima di esclusione e alert sull’assenza di heartbeat.', 'Tamper protection, separated roles, minimal exclusion policy, and alerts on missing heartbeats.'), b('Coverage reconciliation con inventory/MDM e response testata per isolamento e acquisizione.', 'Coverage reconciliation with inventory/MDM and tested response for isolation and acquisition.')],
    verification: [b('Esegui un artefatto benigno controllato e conferma evento, contesto, severità e azione attesa.', 'Run a controlled benign artifact and confirm the expected event, context, severity, and action.'), b('Arresta un sensore di test e verifica che la perdita di copertura sia rilevata separatamente dall’assenza di minacce.', 'Stop a test sensor and verify coverage loss is detected separately from absence of threats.')],
    caveat: b('Agente installato o console “healthy” non prova visibilità completa né capacità di blocco; servono test del sensore e della risposta.', 'An installed agent or “healthy” console does not prove complete visibility or blocking ability; sensor and response tests are required.')
  },
  {
    id: 'endpoint-host-firewall', area: 'firewall', domains: ['network-access', 'security-fundamentals'], planes: ['data', 'application'], techniqueIds: ['east-west-lateral-movement', 'malware-ransomware'], controlIds: ['segmentation-least-reachability', 'endpoint-security-assurance'],
    title: b('Host firewall e traffico east–west', 'Host firewalls and east–west traffic'),
    lifecycle: [b('La policy classifica profilo rete, identità, applicazione, direzione, protocollo e porta.', 'Policy classifies network profile, identity, application, direction, protocol, and port.'), b('Regole locali e centrali si combinano secondo precedenza documentata e producono log verificabili.', 'Local and central rules combine under documented precedence and produce verifiable logs.')],
    threat: b('Regole any/any, profilo rete errato o eccezioni locali consentono amministrazione remota e propagazione laterale.', 'Any/any rules, the wrong network profile, or local exceptions permit remote administration and lateral propagation.'),
    evidence: [b('Policy effettiva, profilo attivo, rule hit, process owner e tuple del flusso.', 'Effective policy, active profile, rule hits, process owner, and flow tuples.'), b('Test allow/deny da peer nello stesso segmento e da segmenti differenti.', 'Allow/deny tests from peers in the same and different segments.')],
    controls: [b('Default inbound deny, eccezioni per ruolo e management ristretto a jump host o strumenti autorizzati.', 'Default inbound deny, role-specific exceptions, and management restricted to authorized jump hosts or tools.'), b('Policy bloccata centralmente, log remoto e parità IPv4/IPv6.', 'Centrally locked policy, remote logging, and IPv4/IPv6 parity.')],
    verification: [b('Prova servizio autorizzato e vietato su entrambe le famiglie IP e correla il risultato alla regola effettiva.', 'Test allowed and denied services over both IP families and correlate results to the effective rule.'), b('Conferma che l’utente standard non possa creare un’eccezione persistente.', 'Confirm a standard user cannot create a persistent exception.')],
    caveat: b('Il firewall host limita il percorso di rete ma non impedisce da solo abuso di un processo già autorizzato o di credenziali valide.', 'A host firewall constrains network paths but does not by itself prevent abuse of an already authorized process or valid credentials.')
  },
  {
    id: 'application-script-control', area: 'application', domains: ['security-fundamentals'], planes: ['application', 'identity'], techniqueIds: ['application-control-bypass', 'malware-ransomware', 'phishing-social-engineering'], controlIds: ['endpoint-security-assurance', 'identity-lifecycle-session-control'],
    title: b('Application control, script e macro', 'Application control, scripts, and macros'),
    lifecycle: [b('La policy decide per firma, publisher, hash, percorso o comportamento quali binari e script possono eseguire.', 'Policy decides by signature, publisher, hash, path, or behavior which binaries and scripts may run.'), b('Interpreter, macro, driver e child process vengono inclusi perché un’app consentita può avviare contenuto non fidato.', 'Interpreters, macros, drivers, and child processes are included because an allowed application may launch untrusted content.')],
    threat: b('Living-off-the-land, DLL side-loading, macro o script abusano di componenti attendibili per aggirare la allowlist.', 'Living-off-the-land, DLL side-loading, macros, or scripts abuse trusted components to bypass the allowlist.'),
    evidence: [b('Firma/publisher/hash, command line, parent-child, user e motivo allow/deny.', 'Signature/publisher/hash, command line, parent-child chain, user, and allow/deny reason.'), b('Eventi script-block/AMSI o equivalenti, file origin e comportamento successivo.', 'Script-block/AMSI or equivalent events, file origin, and subsequent behavior.')],
    controls: [b('Allowlist per ruolo, macro da origini fidate, constrained language e blocco di child process non necessari.', 'Role-based allowlists, macros from trusted origins, constrained language, and blocking of unnecessary child processes.'), b('Policy in audit prima dell’enforcement, eccezioni minime e firma del codice.', 'Policy in audit before enforcement, minimal exceptions, and code signing.')],
    verification: [b('Esegui un’app autorizzata, una non autorizzata e un bypass benigno rappresentativo verificando evento e risultato.', 'Run an authorized application, an unauthorized one, and a representative benign bypass while verifying event and outcome.'), b('Conferma che aggiornamenti legittimi e strumenti amministrativi conservino solo le capacità richieste.', 'Confirm legitimate updates and administrative tools retain only required capabilities.')],
    caveat: b('Un’applicazione firmata o consentita non è automaticamente sicura: può essere vulnerabile, compromessa o abusata come proxy.', 'A signed or allowed application is not automatically safe: it may be vulnerable, compromised, or abused as a proxy.')
  },
  {
    id: 'continuous-posture-access', area: 'posture', domains: ['network-access', 'security-fundamentals'], planes: ['data', 'identity', 'management'], techniqueIds: ['nac-posture-bypass', 'rogue-device'], controlIds: ['dot1x-nac', 'endpoint-security-assurance'],
    title: b('Postura continua e autorizzazione di rete', 'Continuous posture and network authorization'),
    lifecycle: [b('802.1X autentica device o utente e NAC assegna policy iniziale in base a identità e contesto.', '802.1X authenticates the device or user and NAC assigns initial policy based on identity and context.'), b('Posture periodica rivaluta patch, cifratura e sensor health e può cambiare VLAN, SGT o ACL della sessione.', 'Periodic posture reassesses patching, encryption, and sensor health and may change the session VLAN, SGT, or ACL.')],
    threat: b('Una verifica solo al login, MAB permissivo o fail-open mantiene accesso a un endpoint degradato dopo l’ammissione.', 'A login-only check, permissive MAB, or fail-open behavior preserves access for an endpoint that degrades after admission.'),
    evidence: [b('Metodo EAP/MAB, authorization profile, posture timestamp e reason code.', 'EAP/MAB method, authorization profile, posture timestamp, and reason code.'), b('Session change, CoA, VLAN/SGT/dACL effettivi e reachability risultante.', 'Session changes, CoA, effective VLAN/SGT/dACL, and resulting reachability.')],
    controls: [b('EAP-TLS, posture ricorrente, fail mode esplicito e segmenti di remediation minimi.', 'EAP-TLS, recurring posture, an explicit fail mode, and minimal remediation segments.'), b('CoA testata, eccezioni con scadenza e policy coerente su wired, wireless e VPN.', 'Tested CoA, expiring exceptions, and consistent policy across wired, wireless, and VPN access.')],
    verification: [b('Rendi non conforme un endpoint di test e prova cambio policy, reachability minima e ritorno controllato.', 'Make a test endpoint noncompliant and prove policy change, minimal reachability, and controlled return.'), b('Simula indisponibilità NAC/RADIUS e conferma il fail mode previsto senza bypass silenzioso.', 'Simulate NAC/RADIUS unavailability and confirm the intended fail mode without silent bypass.')],
    caveat: b('Postura conforme indica requisiti osservati in un momento; non dimostra che l’endpoint sia privo di compromissione.', 'Compliant posture indicates observed requirements at a point in time; it does not prove the endpoint is uncompromised.')
  },
  {
    id: 'local-privilege-credential-protection', area: 'privilege', domains: ['security-fundamentals'], planes: ['identity', 'application'], techniqueIds: ['credential-attacks', 'privileged-command-abuse', 'mfa-fatigue-token-theft'], controlIds: ['aaa-privileged-access', 'identity-lifecycle-session-control', 'endpoint-security-assurance'],
    title: b('Privilegi locali, credenziali e sessioni', 'Local privileges, credentials, and sessions'),
    lifecycle: [b('Account standard eseguono attività quotidiane; elevazione separata concede privilegi limitati e tracciati.', 'Standard accounts perform daily work; separate elevation grants constrained and audited privileges.'), b('Password locali, token, cache, chiavi e sessioni vengono inventariati, protetti, ruotati e revocati.', 'Local passwords, tokens, caches, keys, and sessions are inventoried, protected, rotated, and revoked.')],
    threat: b('Admin permanente, password locali riutilizzate o token estraibili trasformano un endpoint compromesso in movimento laterale.', 'Standing admin rights, reused local passwords, or extractable tokens turn one compromised endpoint into lateral movement.'),
    evidence: [b('Membership dei gruppi privilegiati, elevation event, account/owner e command/process lineage.', 'Privileged-group membership, elevation events, account/owner, and command/process lineage.'), b('Creazione/uso di credenziali, accessi remoti e sessioni ancora valide dopo revoca.', 'Credential creation/use, remote logons, and sessions still valid after revocation.')],
    controls: [b('Least privilege, account amministrativo separato, JIT/JEA o equivalenti e password locali uniche gestite.', 'Least privilege, separate administrative accounts, JIT/JEA or equivalents, and managed unique local passwords.'), b('Credential protection, MFA resistente al phishing dove applicabile e revoca coordinata di token/sessioni.', 'Credential protection, phishing-resistant MFA where applicable, and coordinated token/session revocation.')],
    verification: [b('Prova che un utente standard non possa eseguire azioni privilegiate e che l’elevazione sia temporanea e registrata.', 'Prove a standard user cannot perform privileged actions and elevation is temporary and audited.'), b('Ruota una password locale o revoca un account di test e verifica l’invalidazione delle vie di accesso correlate.', 'Rotate a test local password or revoke an account and verify related access paths are invalidated.')],
    caveat: b('Rimuovere l’utente da un gruppo non termina automaticamente processi, token e sessioni già privilegiati.', 'Removing a user from a group does not automatically terminate already privileged processes, tokens, and sessions.')
  },
  {
    id: 'endpoint-isolation-readmission', area: 'containment', domains: ['network-access', 'security-fundamentals'], planes: ['data', 'identity', 'management', 'application'], techniqueIds: ['malware-ransomware', 'east-west-lateral-movement', 'session-hijack-reset'], controlIds: ['endpoint-security-assurance', 'segmentation-least-reachability', 'telemetry-independent-evidence'],
    title: b('Isolamento, acquisizione e riammissione', 'Isolation, acquisition, and readmission'),
    lifecycle: [b('EDR, NAC o firewall contengono l’endpoint preservando solo i canali necessari a risposta e gestione.', 'EDR, NAC, or firewalls contain the endpoint while preserving only channels needed for response and management.'), b('Evidenze, identità e blast radius guidano reimage o remediation; la riammissione richiede una baseline pulita verificata.', 'Evidence, identities, and blast radius guide reimaging or remediation; readmission requires a verified clean baseline.')],
    threat: b('Isolamento parziale lascia IPv6, Wi-Fi, VPN o sessioni cloud attive; riammissione prematura ripristina persistenza e propagazione.', 'Partial isolation leaves IPv6, Wi-Fi, VPN, or cloud sessions active; premature readmission restores persistence and propagation.'),
    evidence: [b('Stato di isolamento per interfaccia, sessioni attive, DNS/flow, identity log e timeline EDR.', 'Isolation state by interface, active sessions, DNS/flows, identity logs, and EDR timeline.'), b('Root cause, indicatori, hash dell’immagine, patch/baseline e credential rotation completata.', 'Root cause, indicators, image hashes, patch/baseline state, and completed credential rotation.')],
    controls: [b('Playbook coordinato EDR–NAC–identity, acquisizione forense proporzionata e canale di gestione sicuro.', 'A coordinated EDR–NAC–identity playbook, proportionate forensic acquisition, and a secure management channel.'), b('Reimage da sorgente nota, rotazione di credenziali/sessioni e riammissione a gruppi con monitoring rafforzato.', 'Reimaging from a known source, credential/session rotation, and staged readmission with enhanced monitoring.')],
    verification: [b('Prova che l’endpoint isolato non raggiunga peer o Internet ma resti raggiungibile dal solo servizio di risposta previsto.', 'Prove the isolated endpoint cannot reach peers or the Internet but remains reachable only by the intended response service.'), b('Prima della riammissione verifica baseline, EDR, identità, reachability e assenza di recidiva con un canary.', 'Before readmission, verify baseline, EDR, identity, reachability, and lack of recurrence with a canary.')],
    caveat: b('Isolare la rete non revoca automaticamente token cloud o credenziali; un clean scan non dimostra da solo l’eliminazione della root cause.', 'Network isolation does not automatically revoke cloud tokens or credentials; a clean scan alone does not prove root-cause removal.')
  }
];
