import type { Bilingual } from '../types';
import type { CcnaDomainId } from './securityCoverage';
import type { SecurityPlane } from './securityTaxonomy';

export type ManagementTelemetryArea = 'boundary' | 'ssh' | 'snmp' | 'syslog' | 'time' | 'api' | 'discovery' | 'backup' | 'collectors';

export interface ManagementTelemetryScenario {
  id: string;
  area: ManagementTelemetryArea;
  domains: CcnaDomainId[];
  planes: SecurityPlane[];
  techniqueIds: string[];
  controlIds: string[];
  title: Bilingual;
  trustPath: Bilingual[];
  threat: Bilingual;
  evidence: Bilingual[];
  controls: Bilingual[];
  verification: Bilingual[];
  caveat: Bilingual;
}

const b = (it: string, en: string): Bilingual => ({ it, en });

export const MANAGEMENT_TELEMETRY_SCENARIOS: ManagementTelemetryScenario[] = [
  {
    id: 'management-reachability-boundary', area: 'boundary', domains: ['network-fundamentals', 'ip-services', 'security-fundamentals'], planes: ['management', 'control', 'identity'], techniqueIds: ['management-plane-exposure'], controlIds: ['management-plane-isolation', 'segmentation-least-reachability', 'management-telemetry-assurance'],
    title: b('OOB, management VRF e percorso in-band', 'OOB, management VRF, and in-band path'),
    trustPath: [b('L’amministratore entra da una workstation gestita o da un jump host autenticato.', 'The administrator enters from a managed workstation or authenticated jump host.'), b('ACL, routing e interfaccia sorgente limitano il percorso fino al servizio di gestione del dispositivo.', 'ACLs, routing, and the source interface constrain the path to the device management service.'), b('Un canale OOB indipendente mantiene accesso quando il data plane o il routing in-band non sono disponibili.', 'An independent OOB channel preserves access when the data plane or in-band routing is unavailable.')],
    threat: b('Servizi amministrativi raggiungibili da user, guest o Internet espongono credenziali e controllo del dispositivo.', 'Administrative services reachable from user, guest, or Internet networks expose credentials and device control.'),
    evidence: [b('Test positivo dal jump host e negativo da VLAN user, guest e reti esterne.', 'A positive test from the jump host and negative tests from user, guest, and external networks.'), b('RIB/VRF, ACL hit, service binding e interfaccia sorgente effettiva.', 'The RIB/VRF, ACL hits, service binding, and actual source interface.')],
    controls: [b('OOB fisico dove il requisito lo giustifica, oppure management VRF con infrastructure ACL e CoPP.', 'Physical OOB where justified, or a management VRF with infrastructure ACLs and CoPP.'), b('Jump host, AAA forte, inventario dei servizi e procedure break-glass testate.', 'A jump host, strong AAA, service inventory, and tested break-glass procedures.')],
    verification: [b('Interrompi in modo controllato il percorso in-band e prova l’accesso OOB senza perdere audit e AAA.', 'Controlledly interrupt the in-band path and prove OOB access without losing auditing or AAA.'), b('Esegui lookup e connessione da ogni zona per confermare sia gli allow sia i deny previsti.', 'Run lookups and connections from each zone to confirm intended allows and denies.')],
    caveat: b('Una management VRF condivide apparato, alimentazione e possibili failure domain: non equivale automaticamente a una rete OOB fisica.', 'A management VRF shares the device, power, and possible failure domains: it is not automatically equivalent to a physical OOB network.')
  },
  {
    id: 'ssh-administrative-session', area: 'ssh', domains: ['ip-services', 'security-fundamentals'], planes: ['management', 'identity'], techniqueIds: ['ssh-management-attacks', 'privileged-command-abuse'], controlIds: ['management-plane-isolation', 'aaa-privileged-access', 'management-telemetry-assurance'],
    title: b('SSHv2, VTY, identità e accounting', 'SSHv2, VTY lines, identity, and accounting'),
    trustPath: [b('Il client valida l’host key e negozia algoritmi SSH moderni con il dispositivo corretto.', 'The client validates the host key and negotiates modern SSH algorithms with the correct device.'), b('La VTY ACL limita le sorgenti; AAA autentica, autorizza il ruolo e registra sessione e comandi.', 'The VTY ACL limits sources; AAA authenticates, authorizes the role, and records the session and commands.')],
    threat: b('Password guessing, chiavi sottratte, host key non verificata o fallback locale debole consentono accesso privilegiato.', 'Password guessing, stolen keys, an unverified host key, or weak local fallback permits privileged access.'),
    evidence: [b('Fingerprint host, suite negoziata, source IP, identità AAA e livello di privilegio.', 'The host fingerprint, negotiated suite, source IP, AAA identity, and privilege level.'), b('Accounting di login, logout e comandi correlato alla configuration history.', 'Login, logout, and command accounting correlated with configuration history.')],
    controls: [b('SSHv2, algoritmi moderni, host key gestite, timeout e tentativi limitati.', 'SSHv2, modern algorithms, managed host keys, timeouts, and limited attempts.'), b('VTY ACL, TACACS+ o AAA equivalente, MFA sul percorso amministrativo e fallback break-glass controllato.', 'VTY ACLs, TACACS+ or equivalent AAA, MFA on the administrative path, and controlled break-glass fallback.')],
    verification: [b('Prova un ruolo consentito e uno vietato, verificando command authorization e accounting remoto.', 'Test an allowed and a denied role, verifying remote command authorization and accounting.'), b('Rifiuta una host key cambiata senza change autorizzato e investiga prima di accettarla.', 'Reject a changed host key without an authorized change and investigate before accepting it.')],
    caveat: b('La cifratura SSH protegge il canale, ma non prova autorizzazione e accounting, affidabilità dell’endpoint o legittimità dei comandi.', 'SSH encryption protects the channel, but does not prove authorization and accounting, endpoint trustworthiness, or command legitimacy.')
  },
  {
    id: 'snmpv3-observability', area: 'snmp', domains: ['ip-services', 'security-fundamentals'], planes: ['management', 'identity', 'application'], techniqueIds: ['snmp-community-abuse', 'telemetry-collector-blindness'], controlIds: ['telemetry-independent-evidence', 'management-plane-isolation', 'management-telemetry-assurance'],
    title: b('SNMPv3, viste, polling e notifiche', 'SNMPv3, views, polling, and notifications'),
    trustPath: [b('Il manager autorizzato interroga solo le MIB incluse nella view associata all’utente SNMPv3.', 'The authorized manager queries only MIB objects included in the SNMPv3 user view.'), b('Il dispositivo invia trap o inform verso collector inventariati; il collector correla polling e notifiche.', 'The device sends traps or informs to inventoried collectors; the collector correlates polling and notifications.')],
    threat: b('Community condivise, write access, viste ampie o manager falsi espongono inventario e possono modificare stato.', 'Shared communities, write access, broad views, or rogue managers expose inventory and may modify state.'),
    evidence: [b('Security level authPriv, engine ID, user/view, ACL e source address osservati.', 'Observed authPriv security level, engine ID, user/view, ACL, and source address.'), b('Confronto tra valore SNMP, CLI/API e ricezione di una notifica di test.', 'Comparison among an SNMP value, CLI/API output, and receipt of a test notification.')],
    controls: [b('SNMPv3 authPriv, viste minime, credenziali uniche e nessun write access se non richiesto.', 'SNMPv3 authPriv, minimal views, unique credentials, and no write access unless required.'), b('ACL verso manager noti, rotazione, engine-time monitoring e collector ridondanti.', 'ACLs to known managers, rotation, engine-time monitoring, and redundant collectors.')],
    verification: [b('Conferma che un manager autorizzato legga solo gli OID previsti e che una sorgente non autorizzata fallisca.', 'Confirm an authorized manager reads only intended OIDs and an unauthorized source fails.'), b('Genera un evento benigno e verifica trap/inform, acknowledgement quando applicabile e correlazione con il polling.', 'Generate a benign event and verify the trap/inform, acknowledgement where applicable, and polling correlation.')],
    caveat: b('SNMPv3 authPriv protegge autenticità e confidenzialità del protocollo; view, ACL e least privilege restano necessari.', 'SNMPv3 authPriv protects protocol authenticity and confidentiality; views, ACLs, and least privilege remain necessary.')
  },
  {
    id: 'syslog-pipeline-integrity', area: 'syslog', domains: ['ip-services', 'security-fundamentals'], planes: ['management', 'application'], techniqueIds: ['syslog-manipulation', 'security-log-suppression', 'telemetry-collector-blindness'], controlIds: ['telemetry-independent-evidence', 'management-telemetry-assurance'],
    title: b('Syslog remoto, trasporto e integrità della pipeline', 'Remote Syslog, transport, and pipeline integrity'),
    trustPath: [b('Il dispositivo timestampa e bufferizza localmente gli eventi secondo severity e facility.', 'The device timestamps and buffers events locally according to severity and facility.'), b('Il trasporto consegna al collector remoto, preferibilmente con TLS dove supportato, e il SIEM normalizza senza perdere il messaggio originale.', 'Transport delivers to the remote collector, preferably with TLS where supported, and the SIEM normalizes without losing the original message.')],
    threat: b('Saturazione, UDP loss, parsing errato, injection o cancellazione locale interrompono la timeline e nascondono attività.', 'Saturation, UDP loss, parsing errors, injection, or local deletion break the timeline and hide activity.'),
    evidence: [b('Gap o duplicati di sequenza, queue/drop del sender, listener e pipeline, più differenze local/remote.', 'Sequence gaps or duplicates, sender/listener/pipeline queue drops, and local/remote differences.'), b('Identità del dispositivo, certificato TLS dove usato, timestamp di origine e ingestion time.', 'Device identity, the TLS certificate where used, source timestamp, and ingestion time.')],
    controls: [b('Collector ridondanti, buffering, TLS dove disponibile, storage con integrità e accesso separato.', 'Redundant collectors, buffering, TLS where available, integrity-protected storage, and separate access.'), b('Health check end-to-end, capacity plan, retention e conservazione del raw event.', 'End-to-end health checks, capacity planning, retention, and preservation of the raw event.')],
    verification: [b('Genera un evento campione noto e seguilo da CLI fino a collector, parser, indice e ricerca.', 'Generate a known sample event and follow it from the CLI through the collector, parser, index, and search.'), b('Simula una breve indisponibilità del collector e verifica buffering, replay e allarme di gap senza perdere l’originale.', 'Simulate a brief collector outage and verify buffering, replay, and gap alerting without losing the original.')],
    caveat: b('Ricevere un messaggio Syslog non dimostra che nessun evento sia andato perso prima o dopo: servono sequenze, health e fonti indipendenti.', 'Receiving one Syslog message does not prove that no event was lost before or after it: sequences, health data, and independent sources are required.')
  },
  {
    id: 'trusted-time-correlation', area: 'time', domains: ['ip-services', 'security-fundamentals'], planes: ['management', 'application', 'identity'], techniqueIds: ['ntp-manipulation'], controlIds: ['telemetry-independent-evidence', 'cryptographic-trust', 'management-telemetry-assurance'],
    title: b('Tempo attendibile, NTP e correlazione', 'Trusted time, NTP, and correlation'),
    trustPath: [b('Il dispositivo seleziona sorgenti temporali inventariate e raggiungibili sul percorso di gestione.', 'The device selects inventoried time sources reachable over the management path.'), b('Offset, delay, jitter, stratum e cambio peer vengono monitorati prima che il tempo alimenti log, AAA e PKI.', 'Offset, delay, jitter, stratum, and peer changes are monitored before time feeds logs, AAA, and PKI.')],
    threat: b('Una sorgente falsa o un grande time step altera timeline, scadenze dei certificati, token e protocolli dipendenti dal tempo.', 'A forged source or large time step disrupts timelines, certificate expiry, tokens, and time-dependent protocols.'),
    evidence: [b('Peer selezionato, reachability, stratum, offset, jitter e reference ID.', 'Selected peer, reachability, stratum, offset, jitter, and reference ID.'), b('Confronto con una sorgente indipendente e storico dei cambi di sincronizzazione.', 'Comparison with an independent source and history of synchronization changes.')],
    controls: [b('Sorgenti multiple fidate, ACL, autenticazione NTP o NTS dove supportati e soglie di offset.', 'Multiple trusted sources, ACLs, NTP authentication or NTS where supported, and offset thresholds.'), b('Correzione graduale quando possibile, allarme sul cambio peer e ownership della gerarchia temporale.', 'Gradual correction where possible, alerts on peer changes, and ownership of the time hierarchy.')],
    verification: [b('Confronta l’orologio con due fonti indipendenti e correla uno stesso evento su device e collector.', 'Compare the clock against two independent sources and correlate one event across the device and collector.'), b('Prova il failover della sorgente senza introdurre un time step incompatibile con log, PKI o AAA.', 'Test source failover without introducing a time step incompatible with logs, PKI, or AAA.')],
    caveat: b('Lo stato “synchronized” non prova che la sorgente sia attendibile né ricostruisce un offset errato avvenuto in precedenza.', 'A “synchronized” state does not prove the source is trustworthy or reconstruct a previous incorrect offset.')
  },
  {
    id: 'management-api-intent', area: 'api', domains: ['automation-programmability', 'security-fundamentals'], planes: ['management', 'application', 'identity'], techniqueIds: ['api-auth-token-abuse', 'management-api-schema-abuse', 'automation-supply-chain-drift'], controlIds: ['automation-guardrails', 'identity-lifecycle-session-control', 'management-telemetry-assurance'],
    title: b('NETCONF, RESTCONF, YANG e stato effettivo', 'NETCONF, RESTCONF, YANG, and actual state'),
    trustPath: [b('Il client valida host o certificato e usa SSH/HTTPS verso l’endpoint di gestione autorizzato.', 'The client validates the host or certificate and uses SSH/HTTPS to the authorized management endpoint.'), b('AAA/RBAC e schema YANG limitano operazioni, datastore, risorse e campi modificabili.', 'AAA/RBAC and the YANG schema constrain operations, datastores, resources, and editable fields.'), b('Commit, audit e read-back confrontano intent, configurazione applicata e stato operativo.', 'Commit, auditing, and read-back compare intent, applied configuration, and operational state.')],
    threat: b('Token sovradimensionati, schema non validato o scope dinamico propagano modifiche oltre il device o l’oggetto previsto.', 'Over-scoped tokens, unvalidated schemas, or dynamic scope propagate changes beyond the intended device or object.'),
    evidence: [b('Identità workload, token scope, endpoint, metodo RPC/HTTP, payload hash e response ID.', 'Workload identity, token scope, endpoint, RPC/HTTP method, payload hash, and response ID.'), b('Diff candidato/running, audit del controller e read-back dello stato operativo sui device.', 'Candidate/running diffs, controller auditing, and device operational-state read-back.')],
    controls: [b('Credenziali brevi e scoped, RBAC server-side, schema validation, dry-run, approval e canary.', 'Short-lived scoped credentials, server-side RBAC, schema validation, dry runs, approvals, and canaries.'), b('Target allowlist, stop condition, rollback provato e audit immutabile.', 'Target allowlists, stop conditions, proven rollback, and immutable auditing.')],
    verification: [b('Invia una modifica benigna a un canary e confronta intent, reply, running config e comportamento risultante.', 'Send a benign change to a canary and compare intent, reply, running configuration, and resulting behavior.'), b('Prova che ruolo, token e schema rifiutino device, datastore e campi fuori scope.', 'Prove that the role, token, and schema reject out-of-scope devices, datastores, and fields.')],
    caveat: b('Una risposta HTTP 200 o RPC “ok” prova accettazione della richiesta, non la correttezza dello stato distribuito o del forwarding.', 'An HTTP 200 or RPC “ok” proves request acceptance, not correctness of distributed state or forwarding.')
  },
  {
    id: 'discovery-topology-exposure', area: 'discovery', domains: ['network-access', 'security-fundamentals'], planes: ['data', 'management'], techniqueIds: ['cdp-lldp-enumeration'], controlIds: ['segmentation-least-reachability', 'management-telemetry-assurance'],
    title: b('CDP/LLDP, inventario e informazioni esposte', 'CDP/LLDP, inventory, and exposed information'),
    trustPath: [b('Le interfacce autorizzate scambiano discovery per topologia, voice VLAN, PoE o automazione.', 'Authorized interfaces exchange discovery data for topology, voice VLANs, PoE, or automation.'), b('Il collector confronta neighbor, chassis/port ID e management address con l’inventario atteso.', 'The collector compares neighbors, chassis/port IDs, and management addresses with expected inventory.')],
    threat: b('Annunci su porte non fidate rivelano modello e topologia; neighbor falsi inquinano inventario e automazione.', 'Advertisements on untrusted ports reveal models and topology; forged neighbors pollute inventory and automation.'),
    evidence: [b('Neighbor detail, porta locale/remota, capability, TTL e management address.', 'Neighbor details, local/remote ports, capabilities, TTL, and management address.'), b('Delta tra discovery, switchport/NAC e source of truth.', 'Differences among discovery data, switchport/NAC state, and the source of truth.')],
    controls: [b('CDP/LLDP abilitati solo dove richiesti dal design e disabilitati su confini non fidati.', 'CDP/LLDP enabled only where required by design and disabled at untrusted boundaries.'), b('Port security/NAC, validazione inventory e gestione non raggiungibile dagli indirizzi annunciati.', 'Port security/NAC, inventory validation, and management that is not reachable merely via advertised addresses.')],
    verification: [b('Verifica per ruolo porta quali TLV sono necessari e quali sono realmente trasmessi.', 'Verify by port role which TLVs are required and which are actually transmitted.'), b('Collega un endpoint controllato a una porta non fidata e conferma assenza degli annunci non necessari.', 'Connect a controlled endpoint to an untrusted port and confirm unnecessary advertisements are absent.')],
    caveat: b('Disabilitare discovery ovunque può rompere voice VLAN, inventory o automazione: la decisione deve essere per ruolo e requisito.', 'Disabling discovery everywhere may break voice VLANs, inventory, or automation: the decision must be based on role and requirement.')
  },
  {
    id: 'configuration-backup-recovery', area: 'backup', domains: ['security-fundamentals', 'automation-programmability'], planes: ['management', 'identity'], techniqueIds: ['configuration-backup-exposure', 'automation-supply-chain-drift'], controlIds: ['automation-guardrails', 'cryptographic-trust', 'management-telemetry-assurance'],
    title: b('Backup di configurazione, segreti e restore', 'Configuration backups, secrets, and restore'),
    trustPath: [b('Il sistema acquisisce configurazione e metadata da device autenticati su un canale protetto.', 'The system acquires configuration and metadata from authenticated devices over a protected channel.'), b('Versione, firma/hash, accesso e retention proteggono il repository; un restore controllato riconcilia dipendenze e stato.', 'Versioning, signatures/hashes, access, and retention protect the repository; a controlled restore reconciles dependencies and state.')],
    threat: b('Backup leggibili o modificabili espongono secret, SNMP/AAA, topologia e permettono il ripristino di configurazioni alterate.', 'Readable or modifiable backups expose secrets, SNMP/AAA data, and topology, and enable restoration of altered configurations.'),
    evidence: [b('Device identity, timestamp, version, hash/firma, encryption state e access log del repository.', 'Device identity, timestamp, version, hash/signature, encryption state, and repository access log.'), b('Diff tra source of truth, backup selezionato e running config dopo restore.', 'Diffs among the source of truth, selected backup, and running configuration after restore.')],
    controls: [b('Repository cifrato, least privilege, separazione dei ruoli, immutabilità/versioning e secret handling.', 'An encrypted repository, least privilege, separation of duties, immutability/versioning, and secret handling.'), b('Restore drill, dipendenze documentate, canary e rotazione dei secret potenzialmente esposti.', 'Restore drills, documented dependencies, canaries, and rotation of potentially exposed secrets.')],
    verification: [b('Valida integrità e provenienza, quindi ripristina in lab o canary e confronta configurazione e servizi.', 'Validate integrity and provenance, then restore in a lab or canary and compare configuration and services.'), b('Conferma che accessi e export impediscano a ruoli non autorizzati di leggere secret o sostituire versioni.', 'Confirm access and export controls prevent unauthorized roles from reading secrets or replacing versions.')],
    caveat: b('La presenza di un backup non prova che il restore sia corretto, completo o compatibile con software, PKI e dipendenze correnti.', 'The presence of a backup does not prove the restore is correct, complete, or compatible with current software, PKI, and dependencies.')
  },
  {
    id: 'collector-coverage-blind-spots', area: 'collectors', domains: ['ip-services', 'security-fundamentals'], planes: ['management', 'application', 'data'], techniqueIds: ['telemetry-collector-blindness', 'security-log-suppression'], controlIds: ['telemetry-independent-evidence', 'management-telemetry-assurance'],
    title: b('Collector, sampling e blind spot', 'Collectors, sampling, and blind spots'),
    trustPath: [b('Device e sensori esportano Syslog, SNMP, NetFlow/IPFIX e metriche da punti di osservazione definiti.', 'Devices and sensors export Syslog, SNMP, NetFlow/IPFIX, and metrics from defined observation points.'), b('Collector e SIEM dichiarano sampling, perdita, timestamp, parser e retention prima della correlazione.', 'Collectors and the SIEM expose sampling, loss, timestamps, parsing, and retention before correlation.')],
    threat: b('Sampling, queue overflow, exporter errato o percorso asimmetrico nascondono attività e generano una falsa assenza di evidenza.', 'Sampling, queue overflow, the wrong exporter, or asymmetric paths hide activity and create false absence of evidence.'),
    evidence: [b('Exporter/observation point, template IPFIX, sampling rate, sequence number e drop counter.', 'Exporter/observation point, IPFIX template, sampling rate, sequence numbers, and drop counters.'), b('Confronto tra interface counters, flow records, packet capture, log applicativi ed endpoint.', 'Comparison among interface counters, flow records, packet captures, application logs, and endpoints.')],
    controls: [b('Mappa di copertura, fonti indipendenti, collector ridondanti e allarmi su volume, gap e parser failure.', 'A coverage map, independent sources, redundant collectors, and alerts on volume, gaps, and parser failures.'), b('Sampling documentato per use case, capacity plan e test sintetici end-to-end.', 'Documented sampling by use case, capacity planning, and end-to-end synthetic tests.')],
    verification: [b('Genera traffico benigno noto su ogni percorso critico e verifica presenza, campi e tempi in ciascuna fonte.', 'Generate known benign traffic on each critical path and verify presence, fields, and timing in each source.'), b('Riduci o interrompi un exporter controllato e conferma che health monitoring segnali il blind spot.', 'Reduce or stop a controlled exporter and confirm health monitoring reports the blind spot.')],
    caveat: b('L’assenza di un evento non prova assenza di attività: sampling, perdita, parsing o punto di osservazione errato possono occultarla.', 'Absence of an event does not prove absence of activity: sampling, loss, parsing, or the wrong observation point may hide it.')
  }
];
