import type { Bilingual } from '../types';
import type { SecurityPlane } from './securityTaxonomy';

export type CcnaDomainId = 'network-fundamentals' | 'network-access' | 'ip-connectivity' | 'ip-services' | 'security-fundamentals' | 'automation-programmability';

export interface SecurityTechnique {
  id: string;
  familyId: string;
  domains: CcnaDomainId[];
  planes: SecurityPlane[];
  name: Bilingual;
  attack: Bilingual;
  prevent: Bilingual;
  detect: Bilingual;
  respondRecover: Bilingual;
  verify: Bilingual;
}

const b = (it: string, en: string): Bilingual => ({ it, en });
const t = (
  id: string,
  familyId: string,
  domains: CcnaDomainId[],
  planes: SecurityPlane[],
  name: Bilingual,
  attack: Bilingual,
  prevent: Bilingual,
  detect: Bilingual,
  respondRecover: Bilingual,
  verify: Bilingual
): SecurityTechnique => ({ id, familyId, domains, planes, name, attack, prevent, detect, respondRecover, verify });

export const SECURITY_TECHNIQUES: SecurityTechnique[] = [
  t('network-reconnaissance', 'reconnaissance', ['network-fundamentals', 'security-fundamentals'], ['data', 'management', 'application'], b('Network reconnaissance ed enumerazione', 'Network reconnaissance and enumeration'), b('Scansioni e interrogazioni raccolgono host, porte, servizi, versioni, topologia e identità per preparare azioni successive.', 'Scans and queries collect hosts, ports, services, versions, topology, and identities to prepare follow-on actions.'), b('Riduzione della superficie esposta, ACL/firewall, segmentazione, hardening dei servizi e gestione sicura.', 'Reduced exposed surface, ACLs/firewalls, segmentation, service hardening, and secure management.'), b('Scan distribuiti o sequenziali, errori ripetuti, query insolite e variazioni nel connection rate.', 'Distributed or sequential scans, repeated errors, unusual queries, and connection-rate changes.'), b('Limita o blocca le sorgenti, verifica ciò che è stato enumerato e correggi le esposizioni non necessarie.', 'Rate-limit or block sources, determine what was enumerated, and remove unnecessary exposure.'), b('Firewall/IDS logs · NetFlow · service inventory', 'Firewall/IDS logs · NetFlow · service inventory')),
  t('physical-tapping', 'mitm', ['network-fundamentals'], ['physical', 'data'], b('Intercettazione fisica e cable tapping', 'Physical interception and cable tapping'), b('Un accesso a rame, fibra o porte esposte consente osservazione o inserimento del traffico.', 'Access to copper, fiber, or exposed ports enables traffic observation or insertion.'), b('Controllo fisico, cablaggi protetti, porte inutilizzate disabilitate, cifratura end-to-end.', 'Physical controls, protected cabling, disabled unused ports, and end-to-end encryption.'), b('Ispezioni, tamper evidence, variazioni ottiche/elettriche e inventario delle connessioni.', 'Inspections, tamper evidence, optical/electrical changes, and connection inventory.'), b('Isola il segmento, preserva evidenze, sostituisci il tratto e ruota credenziali esposte.', 'Isolate the segment, preserve evidence, replace the link, and rotate exposed credentials.'), b('Audit fisico · contatori interfaccia', 'Physical audit · interface counters')),
  t('rf-jamming', 'wireless', ['network-access'], ['physical'], b('Jamming e interferenza RF', 'RF jamming and interference'), b('Rumore intenzionale o interferenza satura il canale e riduce la disponibilità wireless.', 'Intentional noise or interference saturates the channel and reduces wireless availability.'), b('Progettazione RF, ridondanza di banda/canale e protezione fisica delle aree.', 'RF design, band/channel redundancy, and physical protection of areas.'), b('Spectrum analysis, WIDS/WIPS e correlazione tra SNR, retry e disassociazioni.', 'Spectrum analysis, WIDS/WIPS, and correlation of SNR, retries, and disassociations.'), b('Localizza la sorgente, cambia canale/banda e coinvolgi le autorità quando necessario.', 'Locate the source, change channel/band, and involve authorities when required.'), b('WLC RF statistics · spectrum analyzer', 'WLC RF statistics · spectrum analyzer')),
  t('rogue-device', 'spoofing', ['network-access', 'security-fundamentals'], ['physical', 'data', 'identity'], b('Dispositivo rogue', 'Rogue device'), b('Un apparato non autorizzato ottiene accesso e introduce bridge, AP o servizi imprevisti.', 'An unauthorized device gains access and introduces unexpected bridges, APs, or services.'), b('802.1X/EAP-TLS, NAC, Port Security, asset inventory e porte inutilizzate shutdown.', '802.1X/EAP-TLS, NAC, Port Security, asset inventory, and shutdown unused ports.'), b('Profiling NAC, MAC churn, LLDP/CDP inventory e scansioni wireless.', 'NAC profiling, MAC churn, LLDP/CDP inventory, and wireless scanning.'), b('Quarantena, identificazione del proprietario, rimozione e verifica delle credenziali.', 'Quarantine, owner identification, removal, and credential review.'), b('show authentication sessions · inventory diff', 'show authentication sessions · inventory diff')),
  t('mac-flooding', 'availability', ['network-access'], ['data'], b('MAC flooding', 'MAC flooding'), b('MAC sorgente numerosi consumano la CAM table e possono causare unknown-unicast flooding.', 'Numerous source MACs consume the CAM table and may cause unknown-unicast flooding.'), b('Port Security, limiti MAC, sticky learning e segmentazione.', 'Port Security, MAC limits, sticky learning, and segmentation.'), b('CAM churn, violation counter e picchi di unknown-unicast.', 'CAM churn, violation counters, and unknown-unicast spikes.'), b('Err-disable/quarantena della porta, pulizia controllata della tabella e analisi del device.', 'Err-disable/quarantine the port, controlled table cleanup, and device analysis.'), b('show mac address-table count · show port-security', 'show mac address-table count · show port-security')),
  t('arp-poisoning', 'mitm', ['network-access'], ['data'], b('ARP poisoning', 'ARP poisoning'), b('Risposte ARP false associano IP attendibili al MAC dell’attaccante per intercettare il traffico.', 'Forged ARP replies associate trusted IPs with the attacker MAC to intercept traffic.'), b('DHCP Snooping + DAI, ARP ACL per host statici, segmentazione e cifratura.', 'DHCP Snooping + DAI, ARP ACLs for static hosts, segmentation, and encryption.'), b('ARP inspection counters, cambi IP–MAC e gratuitous ARP anomali.', 'ARP inspection counters, IP–MAC changes, and abnormal gratuitous ARP.'), b('Isola la porta, ripristina binding/cache e verifica sessioni o credenziali esposte.', 'Isolate the port, restore bindings/caches, and review exposed sessions or credentials.'), b('show ip arp inspection statistics · show ip arp', 'show ip arp inspection statistics · show ip arp')),
  t('vlan-switch-spoofing', 'spoofing', ['network-access'], ['data'], b('VLAN hopping: switch spoofing', 'VLAN hopping: switch spoofing'), b('DTP viene abusato da una porta utente per negoziare un trunk.', 'DTP is abused from a user port to negotiate a trunk.'), b('switchport mode access, nonegotiate, shutdown delle porte inutilizzate.', 'switchport mode access, nonegotiate, and shutdown unused ports.'), b('Trunk inattesi, DTP events e allowed VLAN anomale.', 'Unexpected trunks, DTP events, and abnormal allowed VLANs.'), b('Disabilita la porta, rimuovi il trunk e verifica movimento laterale.', 'Disable the port, remove the trunk, and investigate lateral movement.'), b('show interfaces switchport · show interfaces trunk', 'show interfaces switchport · show interfaces trunk')),
  t('vlan-double-tagging', 'spoofing', ['network-access'], ['data'], b('VLAN hopping: double tagging', 'VLAN hopping: double tagging'), b('Due tag 802.1Q abusano del traffico non taggato della native VLAN, tipicamente in una sola direzione.', 'Two 802.1Q tags abuse untagged native-VLAN traffic, typically in one direction.'), b('Native VLAN dedicata/inutilizzata, pruning e native tagging quando supportato.', 'Dedicated/unused native VLAN, pruning, and native tagging where supported.'), b('Packet capture e traffico tra segmenti non previsto.', 'Packet capture and unexpected inter-segment traffic.'), b('Blocca la sorgente, correggi trunk/native VLAN e ricerca traffico derivato.', 'Block the source, correct trunk/native VLAN settings, and investigate follow-on traffic.'), b('show interfaces trunk · SPAN capture', 'show interfaces trunk · SPAN capture')),
  t('stp-manipulation', 'routing', ['network-access'], ['control', 'data'], b('STP/BPDU manipulation', 'STP/BPDU manipulation'), b('BPDU superiori tentano di rendere root un dispositivo ostile o provocare riconvergenze.', 'Superior BPDUs attempt to make a hostile device root or trigger reconvergence.'), b('Root Guard, BPDU Guard sugli edge, root priority deterministica.', 'Root Guard, BPDU Guard on edge ports, and deterministic root priority.'), b('Root change, topology-change counter e inconsistent ports.', 'Root changes, topology-change counters, and inconsistent ports.'), b('Isola la porta, ripristina root/ruoli e verifica loop o intercettazione.', 'Isolate the port, restore root/roles, and check for loops or interception.'), b('show spanning-tree detail · inconsistentports', 'show spanning-tree detail · inconsistentports')),
  t('dhcp-starvation', 'availability', ['network-access', 'ip-services'], ['data', 'application'], b('DHCP starvation', 'DHCP starvation'), b('Richieste con identità client variabili esauriscono il pool di lease.', 'Requests with changing client identities exhaust the lease pool.'), b('DHCP Snooping rate limit, Port Security e capacità del pool controllata.', 'DHCP Snooping rate limits, Port Security, and controlled pool capacity.'), b('Picchi Discover, binding churn e pool utilization.', 'Discover spikes, binding churn, and pool utilization.'), b('Blocca la porta, libera lease fraudolenti con cautela e ripristina il servizio.', 'Block the port, carefully clear fraudulent leases, and restore service.'), b('show ip dhcp snooping statistics · show ip dhcp pool', 'show ip dhcp snooping statistics · show ip dhcp pool')),
  t('rogue-dhcp', 'spoofing', ['network-access', 'ip-services'], ['data', 'application'], b('Rogue DHCP', 'Rogue DHCP'), b('Un server non autorizzato offre gateway o DNS controllati dall’attaccante.', 'An unauthorized server offers attacker-controlled gateway or DNS settings.'), b('DHCP Snooping con trust solo verso il server legittimo.', 'DHCP Snooping with trust only toward the legitimate server.'), b('Offer da porte untrusted, gateway/DNS inattesi e binding anomali.', 'Offers from untrusted ports, unexpected gateway/DNS, and abnormal bindings.'), b('Rimuovi il server, rinnova i lease e verifica eventuale intercettazione.', 'Remove the server, renew leases, and investigate possible interception.'), b('show ip dhcp snooping binding · packet capture', 'show ip dhcp snooping binding · packet capture')),
  t('ipv6-ra-nd-spoofing', 'spoofing', ['network-fundamentals', 'network-access'], ['control', 'data'], b('Rogue RA e ND spoofing', 'Rogue RA and ND spoofing'), b('Router Advertisement o Neighbor Advertisement falsi alterano gateway e associazioni IPv6.', 'Forged Router or Neighbor Advertisements alter IPv6 gateways and mappings.'), b('RA Guard, DHCPv6 Guard, SAVI/IPv6 Source Guard e segmentazione.', 'RA Guard, DHCPv6 Guard, SAVI/IPv6 Source Guard, and segmentation.'), b('RA da porte client, cambi neighbor cache e prefissi inattesi.', 'RAs from client ports, neighbor-cache changes, and unexpected prefixes.'), b('Isola la sorgente, ripristina cache/configurazione e rivalida i client.', 'Isolate the source, restore caches/configuration, and revalidate clients.'), b('show ipv6 neighbors · RA Guard counters', 'show ipv6 neighbors · RA Guard counters')),
  t('ip-spoofing', 'spoofing', ['network-fundamentals', 'ip-connectivity'], ['data'], b('IP source spoofing', 'IP source spoofing'), b('Il campo sorgente IPv4/IPv6 viene falsificato per nascondere origine o abusare della fiducia.', 'The IPv4/IPv6 source field is forged to hide origin or abuse trust.'), b('BCP 38, ingress/egress ACL e uRPF compatibile con il routing asimmetrico.', 'BCP 38, ingress/egress ACLs, and uRPF compatible with asymmetric routing.'), b('Sorgenti bogon/impossibili e failure uRPF.', 'Bogon/impossible sources and uRPF failures.'), b('Blocca la sorgente/percorso, coordina upstream e analizza eventuali sessioni riflesse.', 'Block the source/path, coordinate upstream, and analyze reflected sessions.'), b('show ip interface | include verify · ACL counters', 'show ip interface | include verify · ACL counters')),
  t('ospf-injection', 'routing', ['ip-connectivity'], ['control'], b('OSPF adjacency e LSA injection', 'OSPF adjacency and LSA injection'), b('Un neighbor non autorizzato introduce LSA, metriche o default route false.', 'An unauthorized neighbor introduces forged LSAs, metrics, or default routes.'), b('Autenticazione OSPF, passive-interface default, filtering di redistribuzione e CoPP.', 'OSPF authentication, passive-interface default, redistribution filtering, and CoPP.'), b('Neighbor/LSDB churn, nuovi advertising router e prefissi critici.', 'Neighbor/LSDB churn, new advertising routers, and critical prefixes.'), b('Rimuovi l’adiacenza, correggi policy e riconvergi dopo aver validato la LSDB.', 'Remove the adjacency, correct policy, and reconverge after validating the LSDB.'), b('show ip ospf neighbor detail · database', 'show ip ospf neighbor detail · database')),
  t('bgp-hijack', 'routing', ['ip-connectivity'], ['control', 'data'], b('BGP prefix hijacking', 'BGP prefix hijacking'), b('Un AS annuncia un prefisso non autorizzato o più specifico e dirotta il traffico.', 'An AS announces an unauthorized or more-specific prefix and diverts traffic.'), b('RPKI origin validation, prefix/max-prefix filter, IRR e policy peer.', 'RPKI origin validation, prefix/max-prefix filters, IRR, and peer policy.'), b('Route monitoring, origin-AS changes e annunci più specifici.', 'Route monitoring, origin-AS changes, and more-specific announcements.'), b('Ritira/filtra l’annuncio, coordina provider e pubblica comunicazioni operative.', 'Withdraw/filter the announcement, coordinate providers, and publish operational communications.'), b('BGP/RPKI monitoring · received-routes', 'BGP/RPKI monitoring · received-routes')),
  t('icmp-redirect-source-route', 'spoofing', ['ip-connectivity'], ['data', 'control'], b('ICMP redirect e IP source routing abuse', 'ICMP redirect and IP source-routing abuse'), b('Messaggi o opzioni influenzano il next hop per aggirare il percorso previsto.', 'Messages or options influence the next hop to bypass the intended path.'), b('no ip redirects dove inutile, no ip source-route e filtering ai confini.', 'no ip redirects where unnecessary, no ip source-route, and boundary filtering.'), b('Redirect inattesi, pacchetti con IP options e cambi host-route.', 'Unexpected redirects, packets with IP options, and host-route changes.'), b('Ripristina route/cache host, blocca la sorgente e verifica intercettazione.', 'Restore host routes/caches, block the source, and investigate interception.'), b('show ip interface · packet capture', 'show ip interface · packet capture')),
  t('syn-flood', 'availability', ['network-fundamentals', 'security-fundamentals'], ['data', 'application'], b('TCP SYN flood', 'TCP SYN flood'), b('Numerosi handshake incompleti consumano backlog e stato di connessione.', 'Numerous incomplete handshakes consume backlog and connection state.'), b('SYN cookies/proxy, rate limit, firewall/DDoS protection e capacità.', 'SYN cookies/proxy, rate limits, firewall/DDoS protection, and capacity.'), b('Rapporto SYN/SYN-ACK/ACK, half-open e backlog utilization.', 'SYN/SYN-ACK/ACK ratios, half-open connections, and backlog utilization.'), b('Attiva mitigazione, filtra upstream e scala/ripristina il servizio.', 'Enable mitigation, filter upstream, and scale/restore service.'), b('show tcp brief · firewall/DDoS telemetry', 'show tcp brief · firewall/DDoS telemetry')),
  t('udp-amplification', 'availability', ['network-fundamentals', 'ip-services'], ['data', 'application'], b('UDP reflection/amplification', 'UDP reflection/amplification'), b('Richieste con sorgente spoofata inducono risposte amplificate verso la vittima.', 'Requests with spoofed sources induce amplified responses toward the victim.'), b('BCP 38, servizi non esposti/open, RRL e protezione DDoS.', 'BCP 38, no exposed/open services, RRL, and DDoS protection.'), b('Asimmetria request/response, sorgenti distribuite e saturazione link.', 'Request/response asymmetry, distributed sources, and link saturation.'), b('Rate-limit/filter upstream, anycast/scrubbing e hardening degli amplificatori.', 'Rate-limit/filter upstream, anycast/scrubbing, and harden amplifiers.'), b('NetFlow · interface rates · service logs', 'NetFlow · interface rates · service logs')),
  t('session-hijack-reset', 'session', ['network-fundamentals', 'security-fundamentals'], ['data', 'application', 'identity'], b('Session hijacking e forged reset', 'Session hijacking and forged reset'), b('Token, tuple o sequence number vengono rubati/indovinati per impersonare o interrompere una sessione.', 'Tokens, tuples, or sequence numbers are stolen/guessed to impersonate or interrupt a session.'), b('TLS, cookie Secure/HttpOnly/SameSite, token rotation e protezioni protocol-specifiche.', 'TLS, Secure/HttpOnly/SameSite cookies, token rotation, and protocol-specific protections.'), b('Token reuse, geografia/device anomali e picchi RST.', 'Token reuse, abnormal geography/devices, and RST spikes.'), b('Revoca sessioni/token, rotazione credenziali e raccolta forense.', 'Revoke sessions/tokens, rotate credentials, and collect forensic evidence.'), b('Session logs · packet capture · IdP telemetry', 'Session logs · packet capture · IdP telemetry')),
  t('dns-poisoning', 'spoofing', ['ip-services'], ['application', 'data'], b('DNS cache poisoning', 'DNS cache poisoning'), b('Risposte falsificate inseriscono record errati nella cache del resolver.', 'Forged responses insert incorrect records into a resolver cache.'), b('DNSSEC validation, resolver aggiornati, randomizzazione e sorgenti autoritative protette.', 'DNSSEC validation, updated resolvers, randomization, and protected authoritative sources.'), b('Mismatch DNSSEC, TTL/record anomali e cambi improvvisi di risposta.', 'DNSSEC mismatches, abnormal TTL/records, and sudden answer changes.'), b('Flusha la cache, correggi la zona/resolver e valuta utenti dirottati.', 'Flush the cache, correct zone/resolver state, and assess redirected users.'), b('dig +dnssec · resolver logs', 'dig +dnssec · resolver logs')),
  t('dns-tunneling', 'injection', ['ip-services'], ['application', 'management'], b('DNS tunneling', 'DNS tunneling'), b('Dati o comandi vengono codificati in query e risposte DNS.', 'Data or commands are encoded in DNS queries and responses.'), b('Resolver aziendali obbligatori, egress policy, allowlist e DNS firewall/RPZ.', 'Enforced enterprise resolvers, egress policy, allowlists, and DNS firewall/RPZ.'), b('Entropia, lunghezza, volume, NXDOMAIN e domini rari.', 'Entropy, length, volume, NXDOMAIN rates, and rare domains.'), b('Blocca dominio/host, isola endpoint e analizza dati potenzialmente esfiltrati.', 'Block domain/host, isolate endpoints, and analyze potentially exfiltrated data.'), b('DNS query analytics · endpoint telemetry', 'DNS query analytics · endpoint telemetry')),
  t('credential-attacks', 'credentials', ['security-fundamentals'], ['identity', 'management', 'application'], b('Brute force, spraying e credential stuffing', 'Brute force, spraying, and credential stuffing'), b('Tentativi o credenziali riutilizzate cercano accesso a identità valide.', 'Attempts or reused credentials seek access to valid identities.'), b('MFA resistente al phishing, password uniche, rate limit e breached-password checks.', 'Phishing-resistant MFA, unique passwords, rate limits, and breached-password checks.'), b('Failure distribuiti, impossible travel e nuovi device/ASN.', 'Distributed failures, impossible travel, and new devices/ASNs.'), b('Blocca/revoca sessioni, reset mirato, indaga accessi e notifica gli utenti.', 'Block/revoke sessions, perform targeted resets, investigate access, and notify users.'), b('AAA/IdP logs · login block counters', 'AAA/IdP logs · login block counters')),
  t('replay', 'session', ['security-fundamentals', 'automation-programmability'], ['application', 'identity'], b('Replay attack', 'Replay attack'), b('Un messaggio o token valido viene catturato e ripresentato per ripetere un’azione.', 'A valid message or token is captured and resubmitted to repeat an action.'), b('Nonce, timestamp, anti-replay window, token breve e idempotency key.', 'Nonces, timestamps, anti-replay windows, short-lived tokens, and idempotency keys.'), b('Duplicate transaction ID, nonce reuse e richieste identiche ravvicinate.', 'Duplicate transaction IDs, nonce reuse, and closely repeated identical requests.'), b('Revoca token/chiavi, annulla operazioni ove possibile e ricostruisci la timeline.', 'Revoke tokens/keys, reverse operations where possible, and reconstruct the timeline.'), b('API gateway logs · IPsec replay counters', 'API gateway logs · IPsec replay counters')),
  t('tls-downgrade-cert-abuse', 'mitm', ['security-fundamentals', 'ip-services'], ['application', 'identity'], b('TLS downgrade e certificate abuse', 'TLS downgrade and certificate abuse'), b('Il traffico viene forzato verso protezioni deboli o un certificato/CA fraudolento.', 'Traffic is forced toward weak protection or a fraudulent certificate/CA.'), b('TLS moderno, HSTS, validazione nome/catena, lifecycle chiavi e CT monitoring.', 'Modern TLS, HSTS, name/chain validation, key lifecycle management, and CT monitoring.'), b('Handshake legacy, certificate mismatch e nuove emissioni CT.', 'Legacy handshakes, certificate mismatches, and new CT issuances.'), b('Revoca/sostituisci certificati e chiavi, blocca endpoint e valuta sessioni intercettate.', 'Revoke/replace certificates and keys, block endpoints, and assess intercepted sessions.'), b('TLS scan · certificate transparency · OCSP', 'TLS scan · certificate transparency · OCSP')),
  t('injection', 'injection', ['security-fundamentals', 'automation-programmability'], ['application', 'management'], b('SQL, command e API injection', 'SQL, command, and API injection'), b('Input non attendibile altera query, comandi, template o payload di automazione.', 'Untrusted input alters queries, commands, templates, or automation payloads.'), b('Query parametrizzate, allowlist/schema, least privilege e separazione interpreter/dati.', 'Parameterized queries, allowlists/schemas, least privilege, and separation of interpreter/data.'), b('WAF/app logs, errori parser, comandi inattesi e pattern di input.', 'WAF/application logs, parser errors, unexpected commands, and input patterns.'), b('Isola il servizio, revoca credenziali, correggi il sink e valuta dati alterati/esfiltrati.', 'Isolate the service, revoke credentials, fix the sink, and assess altered/exfiltrated data.'), b('SAST/DAST · WAF/API logs · DB audit', 'SAST/DAST · WAF/API logs · DB audit')),
  t('xss-csrf', 'injection', ['security-fundamentals'], ['application', 'identity'], b('XSS e CSRF', 'XSS and CSRF'), b('Script o richieste cross-site abusano del browser e della sessione della vittima.', 'Scripts or cross-site requests abuse the victim browser and session.'), b('Output encoding, CSP, sanitization, SameSite e anti-CSRF token.', 'Output encoding, CSP, sanitization, SameSite, and anti-CSRF tokens.'), b('CSP reports, payload nei campi e azioni sensibili senza flusso previsto.', 'CSP reports, payloads in fields, and sensitive actions outside expected flows.'), b('Revoca sessioni, rimuovi contenuti malevoli, correggi rendering/request validation.', 'Revoke sessions, remove malicious content, and fix rendering/request validation.'), b('CSP report endpoint · application logs', 'CSP report endpoint · application logs')),
  t('malware-ransomware', 'availability', ['security-fundamentals'], ['application', 'identity'], b('Malware e ransomware', 'Malware and ransomware'), b('Codice malevolo esegue persistenza, furto, cifratura o interruzione dei sistemi.', 'Malicious code performs persistence, theft, encryption, or system disruption.'), b('Patching, EDR, application control, least privilege, segmentazione e backup isolati.', 'Patching, EDR, application control, least privilege, segmentation, and isolated backups.'), b('Processi/comportamenti anomali, canary file, EDR e traffico C2.', 'Abnormal processes/behavior, canary files, EDR, and C2 traffic.'), b('Isola endpoint, preserva evidenze, eradica, ripristina da backup testati e monitora recidive.', 'Isolate endpoints, preserve evidence, eradicate, restore tested backups, and monitor recurrence.'), b('EDR timeline · backup restore test · network telemetry', 'EDR timeline · backup restore test · network telemetry')),
  t('phishing-social-engineering', 'credentials', ['security-fundamentals'], ['identity', 'application'], b('Phishing e social engineering', 'Phishing and social engineering'), b('Manipolazione umana induce consegna di credenziali, esecuzione o autorizzazione fraudolenta.', 'Human manipulation induces credential disclosure, execution, or fraudulent authorization.'), b('Awareness contestuale, MFA resistente al phishing, procedure out-of-band e mail security.', 'Contextual awareness, phishing-resistant MFA, out-of-band procedures, and email security.'), b('User reporting, domain/lookalike monitoring e anomalie IdP/email.', 'User reporting, domain/lookalike monitoring, and IdP/email anomalies.'), b('Blocca mittente/dominio, revoca sessioni, reset mirato e comunica l’incidente.', 'Block sender/domain, revoke sessions, perform targeted resets, and communicate the incident.'), b('Mail gateway · IdP logs · user reports', 'Mail gateway · IdP logs · user reports')),
  t('evil-twin-deauth', 'wireless', ['network-access', 'security-fundamentals'], ['physical', 'data', 'identity'], b('Evil twin e deauthentication', 'Evil twin and deauthentication'), b('AP clone e frame management falsi attirano o disconnettono i client.', 'Cloned APs and forged management frames attract or disconnect clients.'), b('WPA3-Enterprise, EAP-TLS con server validation, PMF e WIDS/WIPS.', 'WPA3-Enterprise, EAP-TLS with server validation, PMF, and WIDS/WIPS.'), b('BSSID/SSID duplicati, deauth spike e certificati server inattesi.', 'Duplicate BSSID/SSID, deauth spikes, and unexpected server certificates.'), b('Localizza/rimuovi rogue AP, blocca radio/client e ruota credenziali eventualmente esposte.', 'Locate/remove rogue APs, block radio/clients, and rotate possibly exposed credentials.'), b('WLC rogue AP · PMF status · RADIUS logs', 'WLC rogue AP · PMF status · RADIUS logs')),
  t('api-auth-token-abuse', 'automation', ['automation-programmability'], ['management', 'application', 'identity'], b('API authorization e token abuse', 'API authorization and token abuse'), b('Token rubati o controlli object-level deboli consentono azioni oltre il ruolo.', 'Stolen tokens or weak object-level controls permit actions beyond the role.'), b('Scoped short-lived token, workload identity, RBAC/ABAC server-side e secret manager.', 'Scoped short-lived tokens, workload identity, server-side RBAC/ABAC, and secret managers.'), b('API audit, uso token da nuovi workload e accessi object-level anomali.', 'API auditing, token use from new workloads, and abnormal object-level access.'), b('Revoca/ruota token, limita l’identità e valuta tutte le modifiche effettuate.', 'Revoke/rotate tokens, constrain the identity, and assess all performed changes.'), b('API gateway audit · secret scanning', 'API gateway audit · secret scanning')),
  t('controller-compromise', 'automation', ['automation-programmability'], ['management', 'control'], b('Compromissione del controller', 'Controller compromise'), b('Il punto centralizzato viene usato per distribuire policy o configurazioni malevole su larga scala.', 'The centralized point is used to distribute malicious policy or configuration at scale.'), b('Management segmentation, MFA/PAM, HA, hardening, signed artifacts e least privilege.', 'Management segmentation, MFA/PAM, HA, hardening, signed artifacts, and least privilege.'), b('Audit immutabile, config diff, comportamento southbound anomalo e integrity monitoring.', 'Immutable auditing, configuration diffs, abnormal southbound behavior, and integrity monitoring.'), b('Isola controller/canale, passa a procedure di emergenza, ripristina backup e rivalida device.', 'Isolate the controller/channel, switch to emergency procedures, restore backups, and revalidate devices.'), b('Controller audit · device config diff · integrity checks', 'Controller audit · device config diff · integrity checks')),
  t('automation-supply-chain-drift', 'automation', ['automation-programmability'], ['management', 'application'], b('Supply chain, blast radius e configuration drift', 'Supply chain, blast radius, and configuration drift'), b('Moduli compromessi o errori idempotenti solo in apparenza propagano modifiche e divergono dall’intento.', 'Compromised modules or only apparently idempotent errors propagate changes and diverge from intent.'), b('Version pinning, SBOM/firme, lint/test, dry-run, approval, canary e source of truth.', 'Version pinning, SBOM/signatures, lint/tests, dry runs, approvals, canaries, and a source of truth.'), b('Drift detection, artifact provenance, failed convergence e change-rate anomalo.', 'Drift detection, artifact provenance, failed convergence, and abnormal change rates.'), b('Ferma pipeline, rollback, ripristina artifact fidati e riconcilia lo stato.', 'Stop the pipeline, roll back, restore trusted artifacts, and reconcile state.'), b('CI audit · plan/diff · signed artifact verification', 'CI audit · plan/diff · signed artifact verification')),
  t('ai-telemetry-poisoning', 'automation', ['automation-programmability'], ['management', 'application'], b('AI/telemetry poisoning e prompt injection', 'AI/telemetry poisoning and prompt injection'), b('Dati o istruzioni malevoli alterano baseline, analisi o output generati.', 'Malicious data or instructions alter baselines, analysis, or generated output.'), b('Provenienza dati, isolamento tool, input boundaries, least privilege e human approval.', 'Data provenance, tool isolation, input boundaries, least privilege, and human approval.'), b('Model/data drift, output incoerenti, fonte anomala e tool-call fuori policy.', 'Model/data drift, inconsistent output, abnormal sources, and out-of-policy tool calls.'), b('Disabilita automazione, rimuovi dataset/input contaminati, rivalida modello e modifiche.', 'Disable automation, remove contaminated datasets/inputs, and revalidate the model and changes.'), b('AI audit trail · dataset lineage · policy violations', 'AI audit trail · dataset lineage · policy violations'))
];
