import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { AlertOctagon, CheckCircle2, Filter, HeartPulse, Link2, PauseCircle, RotateCcw, ShieldCheck } from 'lucide-react';
import { RECOVERY_SCENARIOS, type RecoveryArea } from '../content/recoveryScenarios';
import { CCNA_DOMAINS } from '../content/ccna';
import { SECURITY_TECHNIQUES } from '../content/securityCoverage';
import type { CcnaDomainId } from '../content/securityCoverage';
import { DEFENSE_CONTROLS } from '../content/defenseControls';
import { useStore } from '../store';

const AREAS: RecoveryArea[] = ['infrastructure', 'layer2', 'routing', 'services', 'wireless', 'identity', 'trust', 'automation', 'endpoint'];
const AREA_LABELS: Record<RecoveryArea, { it: string; en: string }> = {
  infrastructure: { it: 'Infrastruttura', en: 'Infrastructure' }, layer2: { it: 'Layer 2', en: 'Layer 2' }, routing: { it: 'Routing', en: 'Routing' }, services: { it: 'Servizi', en: 'Services' }, wireless: { it: 'Wireless', en: 'Wireless' }, identity: { it: 'Identità e accesso', en: 'Identity and access' }, trust: { it: 'Fiducia e VPN', en: 'Trust and VPN' }, automation: { it: 'Automazione', en: 'Automation' }, endpoint: { it: 'Endpoint', en: 'Endpoint' }
};
const DOMAIN_BY_ID = new Map(CCNA_DOMAINS.map(item => [item.id, item]));
const TECHNIQUE_BY_ID = new Map(SECURITY_TECHNIQUES.map(item => [item.id, item]));
const CONTROL_BY_ID = new Map(DEFENSE_CONTROLS.map(item => [item.id, item]));

export default function ResilienceRecoveryLab() {
  const language = useStore(state => state.language);
  const [area, setArea] = useState<'all' | RecoveryArea>('all');
  const [domain, setDomain] = useState<'all' | CcnaDomainId>('all');
  const filtered = useMemo(() => RECOVERY_SCENARIOS.filter(item => (area === 'all' || item.area === area) && (domain === 'all' || item.domains.includes(domain))), [area, domain]);

  return (
    <div className="space-y-6">
      <header className="rounded-xl border border-slate-200 bg-white p-6 md:p-8"><div className="flex items-start gap-4"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><HeartPulse className="h-6 w-6" aria-hidden="true" /></div><div><p className="eyebrow">DEPEND · CONTINUE · RECOVER · PROVE</p><h1 className="mt-2 text-2xl font-semibold text-slate-900">{language === 'it' ? 'Laboratorio di resilienza e ripristino' : 'Resilience & Recovery Lab'}</h1><p className="mt-2 max-w-4xl text-sm leading-relaxed text-slate-600">{language === 'it' ? 'Esplora come mantenere il servizio minimo, ripristinare dipendenze nell’ordine corretto e dimostrare il recupero con verifiche indipendenti. Raggiungibilità e job completati non equivalgono da soli a servizio sano.' : 'Explore how to maintain minimum service, restore dependencies in the correct order, and prove recovery through independent validation. Reachability and completed jobs alone do not equal a healthy service.'}</p></div></div></header>

      <section className="grid gap-3 sm:grid-cols-3" aria-label={language === 'it' ? 'Riepilogo recovery' : 'Recovery summary'}>{[{ value: RECOVERY_SCENARIOS.length, it: 'Scenari di ripristino', en: 'Recovery scenarios' }, { value: CCNA_DOMAINS.length, it: 'Domini CCNA coperti', en: 'Covered CCNA domains' }, { value: RECOVERY_SCENARIOS.reduce((total, item) => total + item.validation.length, 0), it: 'Prove di validazione', en: 'Validation checks' }].map(item => <div key={item.en} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-2xl font-semibold text-slate-900">{item.value}</p><p className="text-xs text-slate-500">{item[language]}</p></div>)}</section>

      <section className="rounded-xl border border-slate-200 bg-white p-4" aria-labelledby="recovery-filter-title"><h2 id="recovery-filter-title" className="flex items-center gap-2 text-sm font-semibold text-slate-900"><Filter className="h-4 w-4 text-indigo-600" aria-hidden="true" />{language === 'it' ? 'Filtra gli scenari' : 'Filter scenarios'}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-600">{language === 'it' ? 'Area operativa' : 'Operational area'}<select value={area} onChange={event => setArea(event.target.value as 'all' | RecoveryArea)} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"><option value="all">{language === 'it' ? 'Tutte le aree' : 'All areas'}</option>{AREAS.map(item => <option key={item} value={item}>{AREA_LABELS[item][language]}</option>)}</select></label><label className="text-xs text-slate-600">{language === 'it' ? 'Dominio CCNA' : 'CCNA domain'}<select value={domain} onChange={event => setDomain(event.target.value as 'all' | CcnaDomainId)} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"><option value="all">{language === 'it' ? 'Tutti i domini' : 'All domains'}</option>{CCNA_DOMAINS.map(item => <option key={item.id} value={item.id}>{item.number}. {item.title[language]}</option>)}</select></label></div></section>

      <div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-slate-900">{language === 'it' ? 'Procedure di continuità e recovery' : 'Continuity and recovery procedures'}</h2><span className="text-xs font-semibold text-slate-500" aria-live="polite">{filtered.length} {language === 'it' ? 'risultati' : 'results'}</span></div>
      {filtered.length > 0 ? <section className="grid gap-4 xl:grid-cols-2" aria-label={language === 'it' ? 'Scenari di recovery' : 'Recovery scenarios'}>{filtered.map(item => (
        <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-5 deferred-card [contain-intrinsic-height:auto_820px]">
          <div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-100 pb-4"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-teal-700">{AREA_LABELS[item.area][language]}</p><h3 className="mt-1 text-base font-semibold text-slate-900">{item.title[language]}</h3></div><div className="flex flex-wrap justify-end gap-1">{item.domains.map(id => <span key={id} className="rounded-full bg-indigo-50 px-2 py-1 text-[9px] font-semibold text-indigo-800">{DOMAIN_BY_ID.get(id)?.title[language]}</span>)}</div></div>
          <div className="mt-4 rounded-lg border border-rose-100 bg-rose-50/60 p-3 text-rose-950"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider"><AlertOctagon className="h-3.5 w-3.5" aria-hidden="true" />Trigger</p><p className="mt-2 text-xs leading-relaxed">{item.trigger[language]}</p></div>
          <div className="mt-3 grid gap-3 sm:grid-cols-2"><Info icon={Link2} label={language === 'it' ? 'Dipendenze necessarie' : 'Required dependencies'} tone="sky"><ul className="space-y-1.5">{item.dependencies.map(entry => <li key={entry.en}>• {entry[language]}</li>)}</ul></Info><Info icon={ShieldCheck} label={language === 'it' ? 'Continuità minima' : 'Minimum continuity'} tone="teal"><p>{item.minimumContinuity[language]}</p></Info></div>
          <section className="mt-3 rounded-lg border border-violet-100 bg-violet-50/60 p-3 text-violet-950"><h4 className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider"><RotateCcw className="h-3.5 w-3.5" aria-hidden="true" />{language === 'it' ? 'Sequenza di ripristino' : 'Recovery sequence'}</h4><ol className="mt-2 space-y-2 text-xs leading-relaxed">{item.recoverySteps.map((step, index) => <li key={step.en} className="flex gap-2"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-violet-200 text-[9px] font-bold text-violet-900">{index + 1}</span><span>{step[language]}</span></li>)}</ol></section>
          <div className="mt-3 grid gap-3 sm:grid-cols-2"><Info icon={PauseCircle} label={language === 'it' ? 'Condizioni di arresto' : 'Stop conditions'} tone="amber"><ul className="space-y-1.5">{item.stopConditions.map(entry => <li key={entry.en}>• {entry[language]}</li>)}</ul></Info><Info icon={CheckCircle2} label={language === 'it' ? 'Prove prima della chiusura' : 'Proof before closure'} tone="emerald"><ul className="space-y-1.5">{item.validation.map(entry => <li key={entry.en}>• {entry[language]}</li>)}</ul></Info></div>
          <div className="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-3 text-slate-700"><p className="text-[10px] font-semibold uppercase tracking-wider">{language === 'it' ? 'Rischio residuo' : 'Residual risk'}</p><p className="mt-2 text-xs leading-relaxed">{item.residualRisk[language]}</p></div>
          <div className="mt-3 border-t border-slate-100 pt-3 text-[10px] leading-relaxed text-slate-500"><p><strong>{language === 'it' ? 'Tecniche correlate:' : 'Related techniques:'}</strong> {item.techniqueIds.map(id => TECHNIQUE_BY_ID.get(id)?.name[language]).join(' · ')}</p><p className="mt-1"><strong>{language === 'it' ? 'Controlli di supporto:' : 'Supporting controls:'}</strong> {item.controlIds.map(id => CONTROL_BY_ID.get(id)?.name[language]).join(' · ')}</p></div>
        </article>
      ))}</section> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500" role="status">{language === 'it' ? 'Nessuno scenario corrisponde ai filtri.' : 'No scenario matches the filters.'}</div>}
    </div>
  );
}

const TONES = { sky: 'border-sky-100 bg-sky-50/60 text-sky-950', teal: 'border-teal-100 bg-teal-50/60 text-teal-950', amber: 'border-amber-100 bg-amber-50/60 text-amber-950', emerald: 'border-emerald-100 bg-emerald-50/60 text-emerald-950' } as const;
function Info({ icon: Icon, label, tone, children }: { icon: typeof Link2; label: string; tone: keyof typeof TONES; children: ReactNode }) { return <div className={`rounded-lg border p-3 ${TONES[tone]}`}><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider"><Icon className="h-3.5 w-3.5" aria-hidden="true" />{label}</p><div className="mt-2 text-xs leading-relaxed">{children}</div></div>; }
